(function(_ds){var window=this;'use strict';var CQ=function(){var a=_ds.ji(),b=_ds.bi(a.href);_ds.ai(b,"authuser");a=new URL("/_d/signout",a.origin);a=_ds.bi(a.href);_ds.Zh(a,"continue",b.toString());return a.toString()},DQ=function(a){_ds.L(this,a,-1,null,null)},EQ=function(a){_ds.L(this,a,-1,null,null)},FQ=function(){return(0,_ds.T)('<div class="ogb-wrapper ogb-si"><button class="devsite-user-signin button devsite-top-button">Sign in</button></div>')},GQ=function(){return(0,_ds.T)('<devsite-spinner size="32"></devsite-spinner>')},
HQ=function(a){var b=a.name,c=a.Ro,d=a.So,e=a.Dn,g=a.En,k=a.email,m=a.domain,n=a.Lk,q=a.Fm,r=a.Gn;a=a.Po;c='<div class="ogb-wrapper ogb-si"><div class="devsite-user-dialog-signin"><a href="#" class="devsite-user-dialog-toggle" role="button">'+(c?'<img class="devsite-user-dialog-photo-thumbnail" src="'+_ds.V(_ds.cm(c))+'" srcset="'+_ds.V(c)+" 1x, "+_ds.V(d)+' 2x" loading="lazy" alt="'+_ds.V(b)+'">':'<span class="devsite-user-dialog-letter">'+(b?_ds.U(_ds.yl(b).charAt(0)):_ds.U(_ds.yl(k).charAt(0)))+
"</span>")+'</a></div><div class="devsite-user-dialog" role="dialog" aria-modal="true" aria-label="Account Information" aria-hidden="true">';m&&(c+='<div class="devsite-user-dialog-learn-more">This account is managed by <span>'+_ds.U(m)+'</span>. <a href="'+_ds.V(_ds.am(q))+'" target="_blank">',c+="Learn more</a></div>");c+='<div class="devsite-user-dialog-user"><div class="devsite-user-dialog-photo">'+(e?'<img class="devsite-user-dialog-photo-portrait" src="'+_ds.V(_ds.cm(e))+'" srcset="'+_ds.V(e)+
" 1x, "+_ds.V(g)+' 2x" loading="lazy" alt="'+_ds.V(b)+'">':'<span class="devsite-user-dialog-letter">'+(b?_ds.U(_ds.yl(b).charAt(0)):_ds.U(_ds.yl(k).charAt(0)))+"</span>")+'</div><div class="devsite-user-dialog-details">'+(b?'<div class="devsite-user-dialog-name">'+_ds.U(b)+"</div>":"")+'<div class="devsite-user-dialog-email">'+_ds.U(k)+'</div></div><a class="devsite-user-manage" href="'+_ds.V(_ds.am(n))+'" target="_blank">';c=c+'Manage your Google Account</a></div><div class="devsite-user-dialog-buttons"><button class="devsite-user-signin devsite-user-change-account"><svg class="devsite-switch-account-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="#5f6368"><path d="M17 18c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm3.86-2c0 .17-.01.33-.03.49l1.07.82c.1.08.13.21.06.32l-1.03 1.73c-.06.11-.2.16-.32.11l-1.28-.5c-.26.19-.55.36-.87.49l-.19 1.33c0 .12-.11.21-.24.21h-2.06c-.13 0-.23-.09-.26-.21l-.19-1.33c-.31-.12-.6-.29-.87-.49l-1.28.5c-.12.04-.25 0-.32-.11l-1.03-1.73a.26.26 0 0 1 .06-.32l1.09-.82a2.7 2.7 0 0 1 .01-.98l-1.09-.83a.235.235 0 0 1-.06-.32l1.03-1.73c.06-.11.2-.16.32-.11l1.28.5c.26-.19.55-.36.87-.49l.19-1.33c.02-.12.12-.21.25-.21h2.06c.13 0 .24.09.26.21l.19 1.33c.32.12.6.29.87.49l1.28-.5c.12-.04.25 0 .32.11l1.03 1.73c.06.11.03.24-.06.32l-1.09.83c.01.16.03.32.03.49zM10 6c1.1 0 2 .9 2 2s-.9 2-2 2-2-.9-2-2 .9-2 2-2zm1.02 7.05L10 15c-2.7 0-5.8 1.29-6 2.01V18h6l1.05 2H2v-3c0-2.66 5.33-4 8-4 .31 0 .65.02 1.02.05zM10 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4z"/></svg>Switch account</button><button class="devsite-user-signout">Sign out</button></div><div class="devsite-user-dialog-footer"><div class="devsite-user-dialog-footer-link"><a href="'+
(_ds.V(_ds.am(r))+'" target="_blank">');c=c+'Privacy Policy</a></div><div class="devsite-user-dialog-footer-link"><a href="'+(_ds.V(_ds.am(a))+'" target="_blank">');return(0,_ds.T)(c+"Terms of Service</a></div></div></div></div>")},IQ=function(a){var b=a.link,c=a.Ao,d=a.Ci,e="";a.create?(e+='<a href="'+_ds.V(_ds.am(b))+'"'+(d?' target="_blank"':"")+' class="devsite-user-developer-profile"><svg class="google-dev-icon" xmlns="http://www.w3.org/2000/svg" width="28" height="14" fill-rule="nonzero" xmlns:v="https://vecta.io/nano"><path d="M6.948 6.585l4.407-2.54c1.037-.622 1.4-1.92.778-2.956S10.215-.31 9.178.31L1.607 4.72l5.34 1.867z" fill="#ea4335"/><path d="M10.267 13.17c.726 0 1.504-.415 1.867-1.09.622-1.037.26-2.385-.778-2.956L3.733 4.72c-1.037-.622-2.385-.26-2.956.778-.622 1.037-.26 2.385.778 2.956l7.622 4.407c.363.207.726.31 1.09.31z" fill="#4285f4"/><path d="M17.89 13.17c.363 0 .726-.104 1.09-.31L26.6 8.452l-5.34-1.92-4.46 2.593c-1.037.622-1.4 1.92-.778 2.956.363.674 1.09 1.09 1.867 1.09z" fill="#fbbc04"/><path d="M25.51 8.763c.726 0 1.504-.415 1.867-1.09.622-1.037.26-2.385-.778-2.956L18.978.31c-1.037-.622-2.385-.26-2.956.778-.622 1.037-.26 2.385.778 2.956l7.622 4.407c.31.207.674.31 1.09.31z" fill="#0f9d58"/></svg>',
e+='Create Developer Profile<span class="new-notification">New</span></a>'):(e+='<a href="'+_ds.V(_ds.am(b))+'"'+(d?' target="_blank"':"")+' class="devsite-user-developer-profile"><svg class="google-dev-icon" xmlns="http://www.w3.org/2000/svg" width="28" height="14" fill-rule="nonzero" xmlns:v="https://vecta.io/nano"><path d="M6.948 6.585l4.407-2.54c1.037-.622 1.4-1.92.778-2.956S10.215-.31 9.178.31L1.607 4.72l5.34 1.867z" fill="#ea4335"/><path d="M10.267 13.17c.726 0 1.504-.415 1.867-1.09.622-1.037.26-2.385-.778-2.956L3.733 4.72c-1.037-.622-2.385-.26-2.956.778-.622 1.037-.26 2.385.778 2.956l7.622 4.407c.363.207.726.31 1.09.31z" fill="#4285f4"/><path d="M17.89 13.17c.363 0 .726-.104 1.09-.31L26.6 8.452l-5.34-1.92-4.46 2.593c-1.037.622-1.4 1.92-.778 2.956.363.674 1.09 1.09 1.867 1.09z" fill="#fbbc04"/><path d="M25.51 8.763c.726 0 1.504-.415 1.867-1.09.622-1.037.26-2.385-.778-2.956L18.978.31c-1.037-.622-2.385-.26-2.956.778-.622 1.037-.26 2.385.778 2.956l7.622 4.407c.31.207.674.31 1.09.31z" fill="#0f9d58"/></svg>',
e+="Developer Profile",c&&(e+='<span class="new-notification">New</span>'),e+="</a>");return(0,_ds.T)(e)},LQ=function(a){var b=void 0;a=void 0===a?!1:a;b||(b=JQ());return(window.gapi?Promise.resolve():_ds.mi("https://apis.google.com/js/platform.js")).then(function(){return KQ()}).then(function(){a&&(window.gapi.config.update("googleapis.config/auth/useFirstPartyAuth",!0),window.gapi.config.update("googleapis.config/auth/useFirstPartyAuthV2",!0));return window.gapi.client.init(b)}).then(function(){return window.gapi})},
KQ=function(){return new Promise(function(a){window.gapi.load("client:auth2",a)})},MQ=function(a){return(a=document.querySelector("meta[name="+a+"]"))&&a.getAttribute("content")},JQ=function(){var a=MQ("google-signin-client-id"),b=MQ("google-signin-scope");if(a||b)var c={};a&&(c.clientId=a);b&&(c.scope=b);return c},NQ=function(a,b){if(!a)return a;a.startsWith("http")||(a="https://"+a);return a.includes("photo.jpg")?a.replace(/sz=(\d+)$/,"sz="+b):a.replace(/=s\d+-c$/,"=s"+b+"-c")},OQ=function(a){this.h=
a;this.o=!1;this.eventHandler=new _ds.Aj(this);this.j=!1;this.m=null;this.h=a},QQ=function(a){return _ds.ll(a,function c(){var d=this,e,g;return _ds.Qa(c,function(k){if(1==k.h){if(d.m)return k.K(2);e=d.h.hasAttribute("fp-auth");return _ds.v(k,LQ(e),3)}return 2!=k.h?(d.m=k.j,g=d.m.auth2.getAuthInstance(),g.isSignedIn.listen(d.vn.bind(d)),g.currentUser.listen(d.Pi.bind(d)),_ds.v(k,PQ(d),2)):k.return(d.m)})})},RQ=function(a){return _ds.ll(a,function c(){var d,e,g,k,m,n;return _ds.Qa(c,function(q){switch(q.h){case 1:if(!window.caches)return q.return();
_ds.B(q,2);return _ds.v(q,window.caches.open("devsite.pwa_RUNTIME_v2"),4);case 4:d=q.j;_ds.C(q,3);break;case 2:return _ds.D(q),q.return();case 3:if(!d){q.K(0);break}return _ds.v(q,d.keys(),6);case 6:e=q.j,g=_ds.p(e),k=g.next();case 7:if(k.done){q.K(0);break}m=k.value;n=new URL(m.url);if(n.origin!==document.location.origin||"/sw.js"===n.pathname){q.K(8);break}_ds.B(q,11);return _ds.v(q,d.delete(m),13);case 13:_ds.C(q,8);break;case 11:_ds.D(q);case 8:k=g.next(),q.K(7)}})})},SQ=function(a){a.h.removeAttribute("dialog--open");
_ds.Mg(a.h);var b=_ds.lm(FQ);a.eventHandler.listen(b.querySelector(".devsite-user-signin"),"click",function(){return void a.signIn()});a.h.appendChild(b)},TQ=function(a){return _ds.ll(a,function c(){var d=this,e,g,k,m,n,q,r,t,w;return _ds.Qa(c,function(y){if(1==y.h)return e=d,d.h.removeAttribute("dialog--open"),_ds.Mg(d.h),_ds.v(y,QQ(d),2);if(3!=y.h)return g=y.j,k=g.auth2.getAuthInstance(),m=k.currentUser.get(),n=m.getBasicProfile(),q=_ds.lm(HQ,{email:n.getEmail(),Ro:NQ(n.getImageUrl(),32),So:NQ(n.getImageUrl(),
64),Dn:NQ(n.getImageUrl(),96),En:NQ(n.getImageUrl(),192),name:n.getName(),domain:m.getHostedDomain(),Lk:"https://myaccount.google.com/?utm_source=OGB&amp;utm_medium=act",Fm:"https://www.google.com/support/accounts/bin/answer.py?answer=181692",Gn:"https://myaccount.google.com/privacypolicy",Po:"https://myaccount.google.com/termsofservice"}),r=q.querySelector(".devsite-user-change-account"),d.eventHandler.listen(r,"click",function(){e.changeAccount()}),t=q.querySelector(".devsite-user-signout"),d.eventHandler.listen(t,
"click",function(){e.signOut()}),w=q.querySelector(".devsite-user-dialog-toggle"),d.h.appendChild(q),_ds.v(y,_ds.xi(),3);w.classList.add("show");d.h.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));_ds.x(y)})})},PQ=function(a){return _ds.ll(a,function c(){var d=this,e,g,k,m,n,q,r,t,w;return _ds.Qa(c,function(y){switch(y.h){case 1:return _ds.v(y,QQ(d),2);case 2:return e=y.j,g=e.auth2.getAuthInstance(),k=g.currentUser.get(),_ds.v(y,d.isSignedIn(),3);case 3:if(y.j)return n=k.getAuthResponse(!0),
q=n.access_token,r=n.id_token,t=new FormData,t.set("access_token",q),t.set("id_token",r),_ds.B(y,9),_ds.v(y,_ds.ri("/signinv2",t),11);_ds.B(y,6);return _ds.v(y,_ds.ri("/signoutv2"),8);case 8:_ds.C(y,0);break;case 6:m=_ds.D(y);console.log("failed to update server state, signed out:",m);y.K(0);break;case 11:_ds.C(y,10);break;case 9:w=_ds.D(y),console.log("failed to update server state, signed in:",w);case 10:e.client.setToken(n),_ds.x(y)}})})},UQ=function(a){this.h=a;this.m=0;this.j=!1;this.email=this.pe=
"";this.h=a},$Q=function(a){return _ds.ll(a,function c(){var d,e=this,g,k,m;return _ds.Qa(c,function(n){switch(n.h){case 1:return VQ||(VQ=_ds.ri("/profile/ogb")),_ds.B(n,2),_ds.v(n,VQ,4);case 4:d=n.j;_ds.C(n,3);break;case 2:_ds.D(n),e.h.removeAttribute("signed-in"),e.j=!1;case 3:VQ=null;if(!d){n.K(5);break}_ds.B(n,6);g=_ds.xf(DQ,d);return _ds.v(n,WQ(e,g),8);case 8:_ds.C(n,5);break;case 6:_ds.D(n),e.h.removeAttribute("signed-in"),e.j=!1;case 5:return XQ||(XQ=_ds.ri("/profile/user")),_ds.B(n,9),_ds.v(n,
XQ,11);case 11:k=n.j;_ds.C(n,10);break;case 9:_ds.D(n),YQ(e);case 10:XQ=null;if(k)try{m=_ds.xf(EQ,k),e.j=_ds.mf(m,1,!1),e.j?(e.h.setAttribute("signed-in",""),document.body.setAttribute("signed-in",""),e.pe=_ds.N(m,2,""),e.email=m.getEmail()):(e.h.removeAttribute("signed-in"),document.body.removeAttribute("signed-in"),e.pe="",e.email=""),ZQ.resolve()}catch(q){YQ(e)}_ds.x(n)}})})},WQ=function(a,b){return _ds.ll(a,function d(){var e=this,g,k,m,n,q,r,t,w,y;return _ds.Qa(d,function(A){if(1==A.h){_ds.Mg(e.h);
var z=_ds.N(b,4,"");z=z.replace(/@import\surl\([^)]+\);?/,"");var ba=_ds.tg(),la=ba.h,P=ba.createElement("STYLE");P.type="text/css";ba.getElementsByTagName("HEAD")[0].appendChild(P);P.styleSheet?P.styleSheet.cssText=z:P.appendChild(la.createTextNode(z));g=document.createRange().createContextualFragment(_ds.N(b,1,""));k=document.createElement("div");k.classList.add("ogb-wrapper","ogb-pending");k.appendChild(g);e.h.appendChild(k);m=k.querySelectorAll("#gb a");1<m.length?k.classList.add("ogb-so"):(k.classList.add("ogb-si"),
m[0]&&(m[0].setAttribute("id","devsite-signin-btn"),m[0].classList.add("devsite-top-button","button")));_ds.N(b,2,"")&&(n=document.createElement("script"),n.setAttribute("id","ogb-head-script"),document.head.appendChild(n),(q=document.getElementById("ogb-head-script"))&&q.appendChild(document.createTextNode(_ds.N(b,2,""))));_ds.N(b,5,"")&&(r=document.createElement("script"),r.setAttribute("id","ogb-head-script2"),document.head.appendChild(r),(t=document.getElementById("ogb-head-script2"))&&t.appendChild(document.createTextNode(_ds.N(b,
5,""))));_ds.N(b,7,"")&&(w=document.createElement("script"),w.setAttribute("id","ogb-head-script3"),document.head.appendChild(w),(y=document.getElementById("ogb-head-script3"))&&y.appendChild(document.createTextNode(_ds.N(b,7,""))));return _ds.v(A,_ds.xi(),2)}e.jg();k.classList.remove("ogb-pending");_ds.x(A)})})},YQ=function(a){a.h.removeAttribute("signed-in");a.j=!1;_ds.Mg(a.h)},aR=function(){var a=_ds.S.call(this,["devsite-snackbar","devsite-spinner"])||this;a.eventHandler=new _ds.Aj;a.C=null;a.m=
new _ds.sp;a.j=!1;a.o=!1;a.h=null;return a},cR=function(a){a.j||a.eventHandler.listen(document.body,["devsite-page-changed","devsite-content-updated"],function(){a.h&&(a.h.jg(),a.h.Nd())});a.eventHandler.listen(a,"click",function(b){var c=a.querySelector(".devsite-user-dialog-toggle"),d=b.target;c&&c.contains(d)&&(b.preventDefault(),b.stopPropagation(),a.hasAttribute("dialog--open")?a.removeAttribute("dialog--open"):a.setAttribute("dialog--open",""));(b=a.querySelector(".devsite-user-dialog"))&&b.contains(d)&&
(d=d.tagName.toLowerCase(),"button"!==d&&"A"!==d||a.removeAttribute("dialog--open"))});a.eventHandler.listen(a,"devsite-signed-in-state-changed",function(b){b=b.ea;b.detail&&b.detail.signedIn&&bR(a)});a.eventHandler.listen(document.body,"click",function(){a.removeAttribute("dialog--open")})},bR=function(a){return _ds.ll(a,function c(){var d=this,e,g,k,m,n,q,r,t,w,y;return _ds.Qa(c,function(A){switch(A.h){case 1:return d.hasAttribute("enable-profiles")?_ds.v(A,d.isSignedIn(),2):A.return();case 2:e=
A.j;if(!e)return A.return();_ds.B(A,3);return _ds.v(A,d.m.getEligibility(),5);case 5:g=A.j;_ds.C(A,4);break;case 3:_ds.D(A);case 4:if("ELIGIBLE"!==g)return A.return();_ds.B(A,6);return _ds.v(A,d.m.getProfile(),8);case 8:k=A.j;_ds.C(A,7);break;case 6:_ds.D(A);case 7:m=null;if(k){q=!1;if(k.linkedAccounts)try{r=Math.floor(((new Date).getTime()-(new Date(k.linkedAccounts[0].linkedSince)).getTime())/864E5),q=31>r}catch(z){}return _ds.v(A,(0,_ds.Kp)("/u/me"),12)}return _ds.v(A,(0,_ds.Kp)("/u/new"),11);
case 11:n=A.j;m=_ds.lm(IQ,{create:!0,link:n.href,Ci:n.origin!==document.location.origin});A.K(10);break;case 12:t=A.j,m=_ds.lm(IQ,{create:!1,Ao:q,link:t.href,Ci:t.origin!==document.location.origin}),d.o||(d.dispatchEvent(new CustomEvent("devsite-analytics-observation-unfiltered",{detail:{eventData:JSON.stringify({event:"addUserAttributes",practitionerType:k.title||void 0,profileFeedbackEmailOptIn:k.feedbackEmailPref||!1,profileNewsletterEmailOptIn:k.newsletterEmailPref||!1})},bubbles:!0})),d.o=!0);
case 10:m&&(w=d.querySelector(".devsite-user-dialog-buttons"))&&((y=w.querySelector(".devsite-user-developer-profile"))?w.replaceChild(m,y):w.insertBefore(m,w.firstChild)),_ds.x(A)}})})},dR=function(a){_ds.ll(a,function c(){var d=this,e;return _ds.Qa(c,function(g){if(1==g.h){e=d.getAttribute("notification-msg");if(!e)return g.K(0);d.removeAttribute("notification-msg");return _ds.v(g,DevsiteApp.whenReady(),3)}if(4!=g.h)return _ds.v(g,window.customElements.whenDefined("devsite-snackbar"),4);d.dispatchEvent(new CustomEvent("devsite-show-custom-snackbar-msg",
{detail:{msg:e,showClose:!0},bubbles:!0}));_ds.x(g)})})};_ds.G(DQ,_ds.K);_ds.f=DQ.prototype;_ds.f.mW=function(a){var b={jaa:_ds.N(this,1,""),cS:_ds.N(this,2,""),bS:_ds.N(this,3,""),dS:_ds.N(this,4,""),wq:_ds.N(this,5,""),XA:_ds.N(this,6,""),YA:_ds.N(this,7,"")};a&&(b.N=this);return b};
_ds.f.lW=function(){var a=new _ds.H;var b=_ds.N(this,1,"");0<b.length&&_ds.J(a,1,b);b=_ds.N(this,2,"");0<b.length&&_ds.J(a,2,b);b=_ds.N(this,3,"");0<b.length&&_ds.J(a,3,b);b=_ds.N(this,4,"");0<b.length&&_ds.J(a,4,b);b=_ds.N(this,5,"");0<b.length&&_ds.J(a,5,b);b=_ds.N(this,6,"");0<b.length&&_ds.J(a,6,b);b=_ds.N(this,7,"");0<b.length&&_ds.J(a,7,b);return _ds.I(a)};_ds.f.Wea=function(a){return _ds.Q(this,1,a)};_ds.f.Vca=function(a){return _ds.Q(this,2,a)};_ds.f.Uca=function(a){return _ds.Q(this,3,a)};
_ds.f.Wca=function(a){return _ds.Q(this,4,a)};_ds.f.Caa=function(a){return _ds.Q(this,5,a)};_ds.f.cca=function(a){return _ds.Q(this,6,a)};_ds.f.dca=function(a){return _ds.Q(this,7,a)};_ds.G(EQ,_ds.K);_ds.f=EQ.prototype;_ds.f.aX=function(a){var b={isSignedIn:_ds.mf(this,1,!1),pe:_ds.N(this,2,""),email:_ds.N(this,3,"")};a&&(b.N=this);return b};_ds.f.$W=function(){var a=new _ds.H,b;(b=_ds.mf(this,1,!1))&&_ds.$e(a,1,b);b=_ds.N(this,2,"");0<b.length&&_ds.J(a,2,b);b=this.getEmail();0<b.length&&_ds.J(a,3,b);return _ds.I(a)};_ds.f.mda=function(a){return _ds.nf(this,1,a,!1)};_ds.f.Tda=function(a){return _ds.Q(this,2,a)};_ds.f.getEmail=function(){return _ds.N(this,3,"")};
_ds.f.bca=function(a){return _ds.Q(this,3,a)};_ds.f=OQ.prototype;_ds.f.Pi=function(){return _ds.ll(this,function b(){var c=this,d;return _ds.Qa(b,function(e){switch(e.h){case 1:if(c.o)return e.return();c.o=!0;var g=_ds.lm(GQ);_ds.Mg(c.h);c.h.appendChild(g);return _ds.v(e,DevsiteApp.whenReady(),2);case 2:return _ds.v(e,RQ(c),3);case 3:return _ds.v(e,PQ(c),4);case 4:return _ds.v(e,DevsiteApp.reload(),5);case 5:return _ds.v(e,c.isSignedIn(),6);case 6:d=e.j;c.Nd();c.o=!1;if(d)return _ds.v(e,TQ(c),0);SQ(c);e.K(0)}})})};
_ds.f.vn=function(a){return _ds.ll(this,function c(){var d=this;return _ds.Qa(c,function(e){if(d.j===a)return e.return();d.j=a;return _ds.v(e,d.Pi(),0)})})};_ds.f.isSignedIn=function(){return _ds.ll(this,function b(){var c=this,d,e;return _ds.Qa(b,function(g){if(1==g.h)return _ds.v(g,QQ(c),2);d=g.j;e=d.auth2.getAuthInstance();c.j=!!e.isSignedIn.get();return g.return(Promise.resolve(c.j))})})};
_ds.f.signOut=function(){return _ds.ll(this,function b(){var c=this,d,e;return _ds.Qa(b,function(g){switch(g.h){case 1:return _ds.v(g,QQ(c),2);case 2:return d=g.j,e=d.auth2.getAuthInstance(),_ds.B(g,3,4),_ds.v(g,e.signOut(),6);case 6:c.j=!1,SQ(c);case 4:return _ds.Aa(g),_ds.v(g,DevsiteApp.reload(),7);case 7:_ds.Ba(g,0);break;case 3:return _ds.D(g),_ds.v(g,c.refresh(),4)}})})};
_ds.f.changeAccount=function(){return _ds.ll(this,function b(){var c=this,d,e,g;return _ds.Qa(b,function(k){switch(k.h){case 1:return _ds.v(k,QQ(c),2);case 2:return d=k.j,e=d.auth2.getAuthInstance(),_ds.B(k,3),_ds.v(k,e.signIn({prompt:"select_account"}),5);case 5:_ds.C(k,0);break;case 3:g=_ds.D(k),"popup_closed_by_user"!==g.error&&console.log("error changeAccount",g),_ds.x(k)}})})};
_ds.f.getAccessToken=function(){return _ds.ll(this,function b(){var c=this,d,e,g;return _ds.Qa(b,function(k){if(1==k.h)return _ds.v(k,DevsiteApp.whenReady(),2);if(3!=k.h)return(d=c.h.hasAttribute("fp-auth"))&&"DEV"!==DevsiteApp.getEnv()?k.return(Promise.resolve("")):_ds.v(k,QQ(c),3);e=k.j;return(g=e.client.getToken())?k.return(Promise.resolve(e.client.getToken().access_token)):k.return(Promise.reject("No Access Token"))})})};
_ds.f.refresh=function(){return _ds.ll(this,function b(){var c=this,d;return _ds.Qa(b,function(e){if(1==e.h)return _ds.v(e,c.isSignedIn(),2);d=e.j;return d?_ds.v(e,TQ(c),0):(SQ(c),e.K(0))})})};
_ds.f.signIn=function(){return _ds.ll(this,function b(){var c=this,d,e,g,k,m;return _ds.Qa(b,function(n){switch(n.h){case 1:return _ds.v(n,QQ(c),2);case 2:return d=n.j,e=d.auth2.getAuthInstance(),_ds.B(n,3),_ds.v(n,e.signIn({prompt:"login"}),5);case 5:g=n.j;_ds.C(n,4);break;case 3:k=_ds.D(n),console.log("Error signing in",k),"popup_blocked_by_browser"===k.error&&console.log("Popup was blocked by the browser"),"immediate_failed"===k.error&&console.log("Popup immediately failed");case 4:if(!(m=g)){n.K(6);
break}return _ds.v(n,c.isSignedIn(),7);case 7:m=n.j;case 6:return m?_ds.v(n,TQ(c),0):_ds.v(n,c.refresh(),0)}})})};_ds.f.getAccountName=function(){return _ds.ll(this,function b(){var c=this,d,e,g,k;return _ds.Qa(b,function(m){if(1==m.h)return _ds.v(m,QQ(c),2);d=m.j;e=d.auth2.getAuthInstance();g=e.currentUser.get();return(k=g.getBasicProfile())?m.return(k.getName()):m.return("")})})};
_ds.f.getAccountEmail=function(){return _ds.ll(this,function b(){var c=this,d,e,g,k;return _ds.Qa(b,function(m){if(1==m.h)return _ds.v(m,QQ(c),2);d=m.j;e=d.auth2.getAuthInstance();g=e.currentUser.get();return(k=g.getBasicProfile())?m.return(k.getEmail()):m.return("")})})};
_ds.f.getAccountId=function(){return _ds.ll(this,function b(){var c=this,d,e,g,k;return _ds.Qa(b,function(m){if(1==m.h)return _ds.v(m,QQ(c),2);d=m.j;e=d.auth2.getAuthInstance();g=e.currentUser.get();return(k=g.getBasicProfile())?m.return(k.getId()):m.return("")})})};_ds.f.dispose=function(){this.m=null;_ds.Gj(this.eventHandler);this.j=!1};_ds.f.Nd=function(){this.h.dispatchEvent(new CustomEvent("devsite-signed-in-state-changed",{detail:{signedIn:this.j,gapiSignIn:!0},bubbles:!0}))};_ds.f.jg=function(){};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var eR="",fR="",XQ=null,VQ=null,gR="",hR=null,ZQ=new _ds.Rp;_ds.f=UQ.prototype;_ds.f.Nd=function(){eR&&this.h.setAttribute("sign-in-url",eR);fR&&this.h.setAttribute("sign-out-url",fR);var a=this.h.hasAttribute("signed-in"),b=a?eR:fR,c=a?1:2;b?this.h.setAttribute("url",b):this.h.removeAttribute("url");c!==this.m&&(this.h.dispatchEvent(new CustomEvent("devsite-signed-in-state-changed",{detail:{signedIn:a,signInUrl:eR,signOutUrl:fR,url:b},bubbles:!0})),this.m=c)};
_ds.f.jg=function(){var a=_ds.ji(),b=_ds.bi(a.href);_ds.ai(b,"authuser");var c=new URL("/_d/signin",a.origin);c=_ds.bi(c.href);_ds.Zh(c,"continue",b.toString());_ds.Zh(c,"prompt","select_account");eR=c.toString();b=Array.from(this.h.querySelectorAll(".devsite-user-signin"));c=_ds.p(b);for(b=c.next();!b.done;b=c.next())_ds.Fd(b.value,eR);fR=CQ();b=Array.from(this.h.querySelectorAll(".devsite-user-signout"));c=_ds.p(b);for(b=c.next();!b.done;b=c.next())_ds.Fd(b.value,fR);Array.from(this.h.querySelectorAll("#gb a")).forEach(function(d){try{var e=
new URL(d.href,document.location.origin)}catch(g){return}e.origin===a.origin&&e.pathname.startsWith("/_ah/logout")&&_ds.Fd(d,fR)});this.h.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}))};_ds.f.refresh=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){if(1==d.h)return _ds.v(d,$Q(c),2);if(3!=d.h)return _ds.v(d,_ds.xi(),3);c.Nd();_ds.x(d)})})};
_ds.f.getAccountName=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return 1==d.h?_ds.v(d,ZQ.h,2):d.return(Promise.resolve(c.pe))})})};_ds.f.getAccountEmail=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return 1==d.h?_ds.v(d,ZQ.h,2):d.return(Promise.resolve(c.email))})})};_ds.f.getAccountId=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return 1==d.h?_ds.v(d,ZQ.h,2):d.return(Promise.resolve(c.email))})})};
_ds.f.isSignedIn=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return 1==d.h?_ds.v(d,ZQ.h,2):d.return(Promise.resolve(c.j))})})};_ds.f.signIn=function(){var a=_ds.ji(),b=_ds.bi(a.href);_ds.ai(b,"authuser");a=new URL("/_d/signin",a.origin);a=_ds.bi(a.href);_ds.Zh(a,"continue",b.toString());_ds.Jd(a.toString())};
_ds.f.changeAccount=function(){var a=_ds.ji(),b=_ds.bi(a.href);_ds.ai(b,"authuser");a=new URL("/_d/signin",a.origin);a=_ds.bi(a.href);_ds.Zh(a,"prompt","select_account");_ds.Zh(a,"continue",b.toString());_ds.Jd(a.toString())};_ds.f.signOut=function(){_ds.Jd(CQ())};
_ds.f.getAccessToken=function(){return _ds.ll(this,function b(){var c=this,d;return _ds.Qa(b,function(e){switch(e.h){case 1:return _ds.v(e,DevsiteApp.whenReady(),2);case 2:return(d=c.h.hasAttribute("fp-auth"))&&"DEV"!==DevsiteApp.getEnv()?e.return(Promise.resolve("")):gR?e.return(gR):_ds.v(e,ZQ.h,3);case 3:return hR||(hR=_ds.ri("/accesstoken")),_ds.B(e,4),_ds.v(e,hR,6);case 6:gR=e.j;_ds.C(e,5);break;case 4:return _ds.D(e),e.return(Promise.reject("No Access Token"));case 5:return e.return(Promise.resolve(gR))}})})};
_ds.f.dispose=function(){};_ds.u(aR,_ds.S);_ds.f=aR.prototype;_ds.f.attributeChangedCallback=function(a){"dialog--open"===a&&this.j&&(a=this.querySelector(".devsite-user-dialog"))&&(this.hasAttribute("dialog--open")?a.setAttribute("aria-hidden","false"):a.setAttribute("aria-hidden","true"))};
_ds.f.connectedCallback=function(){if("devsite-user"!==this.id){var a=document.querySelector("devsite-user#devsite-user");if(a&&a!==this)for(var b=0;b<a.attributes.length;b++){var c=a.attributes[b];"id"!==c.name&&this.setAttribute(c.name,c.value)}}(this.j=this.hasAttribute("js-signin"))?this.h=new OQ(this):this.h=new UQ(this);cR(this);this.refresh();dR(this)};_ds.f.disconnectedCallback=function(){_ds.Gj(this.eventHandler)};_ds.f.isSignedIn=function(){return this.h?this.h.isSignedIn():Promise.resolve(!1)};
_ds.f.signIn=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){c.removeAttribute("dialog--open");return c.h?_ds.v(d,c.h.signIn(),0):d.K(0)})})};_ds.f.changeAccount=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){c.removeAttribute("dialog--open");return c.h?_ds.v(d,c.h.changeAccount(),0):d.K(0)})})};_ds.f.signOut=function(){this.removeAttribute("dialog--open");this.h&&this.h.signOut()};
_ds.f.getAccessToken=function(){return this.h?this.h.getAccessToken():Promise.reject("No auth service.")};_ds.f.getAccountName=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return c.h?d.return(c.h.getAccountName()):d.return("")})})};_ds.f.getAccountEmail=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return c.h?d.return(c.h.getAccountEmail()):d.return("")})})};
_ds.f.getAccountId=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return c.h?d.return(c.h.getAccountId()):d.return("")})})};_ds.f.refresh=function(){return _ds.ll(this,function b(){var c=this;return _ds.Qa(b,function(d){return 1==d.h?(c.removeAttribute("dialog--open"),c.h?_ds.v(d,c.h.refresh(),2):d.K(2)):_ds.v(d,bR(c),0)})})};_ds.f.dispose=function(){this.h&&this.h.dispose()};_ds.l.Object.defineProperties(aR,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dialog--open"]}}});
aR.prototype.refresh=aR.prototype.refresh;aR.prototype.getAccountId=aR.prototype.getAccountId;aR.prototype.getAccountEmail=aR.prototype.getAccountEmail;aR.prototype.getAccountName=aR.prototype.getAccountName;aR.prototype.getAccessToken=aR.prototype.getAccessToken;aR.prototype.signOut=aR.prototype.signOut;aR.prototype.changeAccount=aR.prototype.changeAccount;aR.prototype.signIn=aR.prototype.signIn;aR.prototype.isSignedIn=aR.prototype.isSignedIn;aR.prototype.disconnectedCallback=aR.prototype.disconnectedCallback;
aR.prototype.connectedCallback=aR.prototype.connectedCallback;try{window.customElements.define("devsite-user",aR)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteUser",a)};})(_ds_www);
