(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function ea(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
ea("Symbol",function(a){function b(e){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(e||"")+"_"+d++,e)}function c(e,g){this.a=e;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.a};var d=0;return b});
ea("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return fa(aa(this))}})}return a});function fa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function n(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ha(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function ia(){this.h=!1;this.f=null;this.j=void 0;this.a=1;this.g=this.c=0;this.i=this.b=null}function ja(a){if(a.h)throw new TypeError("Generator is already running");a.h=!0}f=ia.prototype;f.D=function(a){this.j=a};function ka(a,b){a.b={N:b,O:!0};a.a=a.c||a.g}
f.return=function(a){this.b={return:a};this.a=this.g};f.Oa=function(a){this.b={u:a};this.a=this.g};function q(a,b,c){a.a=c;return{value:b}}f.Gc=function(a,b){a=n(a);var c=a.next();ha(c);if(c.done)this.j=c.value,this.a=b;else return this.f=a,q(this,c.value,b)};f.u=function(a){this.a=a};f.Pa=function(){this.a=0};f.gb=function(a){this.c=0;this.g=a||0};function la(a,b){a.a=b;a.c=0}function ma(a){a.c=0;var b=a.b.N;a.b=null;return b}
f.ca=function(a,b,c){c?this.i[c]=this.b:this.i=[this.b];this.c=a||0;this.g=b||0};f.Qa=function(a,b){b=this.i.splice(b||0)[0];(b=this.b=this.b||b)?b.O?this.a=this.c||this.g:void 0!=b.u&&this.g<b.u?(this.a=b.u,this.b=null):this.a=this.g:this.a=a};f.fa=function(a){return new na(a)};function na(a){this.b=a;this.a=[];for(var b in a)this.a.push(b);this.a.reverse()}na.prototype.c=function(){for(;0<this.a.length;){var a=this.a.pop();if(a in this.b)return a}return null};
function oa(a){this.a=new ia;this.b=a}function pa(a,b){ja(a.a);var c=a.a.f;if(c)return qa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.a.return);a.a.return(b);return ra(a)}function qa(a,b,c,d){try{var e=b.call(a.a.f,c);ha(e);if(!e.done)return a.a.h=!1,e;var g=e.value}catch(h){return a.a.f=null,ka(a.a,h),ra(a)}a.a.f=null;d.call(a.a,g);return ra(a)}
function ra(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.h=!1,{value:b.value,done:!1}}catch(c){a.a.j=void 0,ka(a.a,c)}a.a.h=!1;if(a.a.b){b=a.a.b;a.a.b=null;if(b.O)throw b.N;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function sa(a){this.next=function(b){ja(a.a);a.a.f?b=qa(a,a.a.f.next,b,a.a.D):(a.a.D(b),b=ra(a));return b};this.throw=function(b){ja(a.a);a.a.f?b=qa(a,a.a.f["throw"],b,a.a.D):(ka(a.a,b),b=ra(a));return b};this.return=function(b){return pa(a,b)};this[Symbol.iterator]=function(){return this}}function ta(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(g,e)}g(a.next())})}
ea("Promise",function(a){function b(h){this.b=0;this.g=void 0;this.a=[];var k=this.c();try{h(k.resolve,k.reject)}catch(l){k.reject(l)}}function c(){this.a=null}function d(h){return h instanceof b?h:new b(function(k){k(h)})}if(a)return a;c.prototype.b=function(h){if(null==this.a){this.a=[];var k=this;this.c(function(){k.g()})}this.a.push(h)};var e=da.setTimeout;c.prototype.c=function(h){e(h,0)};c.prototype.g=function(){for(;this.a&&this.a.length;){var h=this.a;this.a=[];for(var k=0;k<h.length;++k){var l=
h[k];h[k]=null;try{l()}catch(m){this.f(m)}}}this.a=null};c.prototype.f=function(h){this.c(function(){throw h;})};b.prototype.c=function(){function h(m){return function(p){l||(l=!0,m.call(k,p))}}var k=this,l=!1;return{resolve:h(this.I),reject:h(this.f)}};b.prototype.I=function(h){if(h===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof b)this.J(h);else{a:switch(typeof h){case "object":var k=null!=h;break a;case "function":k=!0;break a;default:k=!1}k?this.v(h):this.h(h)}};
b.prototype.v=function(h){var k=void 0;try{k=h.then}catch(l){this.f(l);return}"function"==typeof k?this.L(k,h):this.h(h)};b.prototype.f=function(h){this.i(2,h)};b.prototype.h=function(h){this.i(1,h)};b.prototype.i=function(h,k){if(0!=this.b)throw Error("Cannot settle("+h+", "+k+"): Promise already settled in state"+this.b);this.b=h;this.g=k;this.j()};b.prototype.j=function(){if(null!=this.a){for(var h=0;h<this.a.length;++h)g.b(this.a[h]);this.a=null}};var g=new c;b.prototype.J=function(h){var k=this.c();
h.C(k.resolve,k.reject)};b.prototype.L=function(h,k){var l=this.c();try{h.call(k,l.resolve,l.reject)}catch(m){l.reject(m)}};b.prototype.then=function(h,k){function l(I,S){return"function"==typeof I?function(Na){try{m(I(Na))}catch(Oa){p(Oa)}}:S}var m,p,H=new b(function(I,S){m=I;p=S});this.C(l(h,m),l(k,p));return H};b.prototype.catch=function(h){return this.then(void 0,h)};b.prototype.C=function(h,k){function l(){switch(m.b){case 1:h(m.g);break;case 2:k(m.g);break;default:throw Error("Unexpected state: "+
m.b);}}var m=this;null==this.a?g.b(l):this.a.push(l)};b.resolve=d;b.reject=function(h){return new b(function(k,l){l(h)})};b.race=function(h){return new b(function(k,l){for(var m=n(h),p=m.next();!p.done;p=m.next())d(p.value).C(k,l)})};b.all=function(h){var k=n(h),l=k.next();return l.done?d([]):new b(function(m,p){function H(Na){return function(Oa){I[Na]=Oa;S--;0==S&&m(I)}}var I=[],S=0;do I.push(void 0),S++,d(l.value).C(H(I.length-1),p),l=k.next();while(!l.done)})};return b});
function r(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
ea("WeakMap",function(a){function b(l){this.a=(k+=Math.random()+1).toString();if(l){l=n(l);for(var m;!(m=l.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(l){var m=typeof l;return"object"===m&&null!==l||"function"===m}function e(l){if(!r(l,h)){var m=new c;ba(l,h,{value:m})}}function g(l){var m=Object[l];m&&(Object[l]=function(p){if(p instanceof c)return p;Object.isExtensible(p)&&e(p);return m(p)})}if(function(){if(!a||!Object.seal)return!1;try{var l=Object.seal({}),m=Object.seal({}),
p=new a([[l,2],[m,3]]);if(2!=p.get(l)||3!=p.get(m))return!1;p.delete(l);p.set(m,4);return!p.has(l)&&4==p.get(m)}catch(H){return!1}}())return a;var h="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var k=0;b.prototype.set=function(l,m){if(!d(l))throw Error("Invalid WeakMap key");e(l);if(!r(l,h))throw Error("WeakMap key fail: "+l);l[h][this.a]=m;return this};b.prototype.get=function(l){return d(l)&&r(l,h)?l[h][this.a]:void 0};b.prototype.has=function(l){return d(l)&&r(l,
h)&&r(l[h],this.a)};b.prototype.delete=function(l){return d(l)&&r(l,h)&&r(l[h],this.a)?delete l[h][this.a]:!1};return b});
ea("Map",function(a){function b(){var k={};return k.o=k.next=k.head=k}function c(k,l){var m=k.a;return fa(function(){if(m){for(;m.head!=k.a;)m=m.o;for(;m.next!=m.head;)return m=m.next,{done:!1,value:l(m)};m=null}return{done:!0,value:void 0}})}function d(k,l){var m=l&&typeof l;"object"==m||"function"==m?g.has(l)?m=g.get(l):(m=""+ ++h,g.set(l,m)):m="p_"+l;var p=k.b[m];if(p&&r(k.b,m))for(k=0;k<p.length;k++){var H=p[k];if(l!==l&&H.key!==H.key||l===H.key)return{id:m,list:p,index:k,l:H}}return{id:m,list:p,
index:-1,l:void 0}}function e(k){this.b={};this.a=b();this.size=0;if(k){k=n(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var k=Object.seal({x:4}),l=new a(n([[k,"s"]]));if("s"!=l.get(k)||1!=l.size||l.get({x:4})||l.set({x:4},"t")!=l||2!=l.size)return!1;var m=l.entries(),p=m.next();if(p.done||p.value[0]!=k||"s"!=p.value[1])return!1;p=m.next();return p.done||4!=p.value[0].x||
"t"!=p.value[1]||!m.next().done?!1:!0}catch(H){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(k,l){k=0===k?0:k;var m=d(this,k);m.list||(m.list=this.b[m.id]=[]);m.l?m.l.value=l:(m.l={next:this.a,o:this.a.o,head:this.a,key:k,value:l},m.list.push(m.l),this.a.o.next=m.l,this.a.o=m.l,this.size++);return this};e.prototype.delete=function(k){k=d(this,k);return k.l&&k.list?(k.list.splice(k.index,1),k.list.length||delete this.b[k.id],k.l.o.next=k.l.next,k.l.next.o=k.l.o,k.l.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.o=b();this.size=0};e.prototype.has=function(k){return!!d(this,k).l};e.prototype.get=function(k){return(k=d(this,k).l)&&k.value};e.prototype.entries=function(){return c(this,function(k){return[k.key,k.value]})};e.prototype.keys=function(){return c(this,function(k){return k.key})};e.prototype.values=function(){return c(this,function(k){return k.value})};e.prototype.forEach=function(k,l){for(var m=this.entries(),p;!(p=m.next()).done;)p=p.value,
k.call(l,p[1],p[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});var t=this||self;function ua(){}function va(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}function wa(a){var b=va(a);return"array"==b||"object"==b&&"number"==typeof a.length}function xa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function ya(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var za=Date.now;function u(a,b){a=a.split(".");var c=t;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function Aa(a,b){function c(){}c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.W=function(d,e,g){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var v=new Map([]);v.set("devsite-analytics",{src:"/js/devsite_devsite_analytics_module.js"});v.set("devsite-analytics-scope",{src:"/js/devsite_devsite_analytics_scope_module.js"});v.set("devsite-anselm",{src:"/js/devsite_devsite_anselm_module.js"});v.set("devsite-api-getstarted",{src:"/js/devsite_devsite_api_getstarted_module.js"});v.set("devsite-apix",{src:"/js/devsite_devsite_apix_module.js"});v.set("devsite-apix-index",{src:"/js/devsite_devsite_apix_index_module.js"});
v.set("devsite-apix-snippets",{src:"/js/devsite_devsite_apix_snippets_module.js"});v.set("devsite-badger",{src:"/js/devsite_devsite_badger_module.js"});v.set("devsite-badge-awarded",{src:"/js/devsite_devsite_badge_awarded_module.js"});v.set("devsite-badge-awarder",{src:"/js/devsite_devsite_badge_awarder_module.js"});v.set("devsite-badge-redeemer",{src:"/js/devsite_devsite_badge_redeemer_module.js"});v.set("devsite-book-nav",{src:"/js/devsite_devsite_book_nav_module.js"});v.set("devsite-chart",{src:"/js/devsite_devsite_chart_module.js"});
v.set("devsite-code",{src:"/js/devsite_devsite_code_module.js"});v.set("devsite-content",{src:"/js/devsite_devsite_content_module.js"});v.set("devsite-catalog",{src:"/js/devsite_devsite_catalog_module.js"});v.set("devsite-credentials-dialog",{src:"/js/devsite_devsite_credentials_dialog_module.js"});v.set("devsite-cse",{src:"/js/devsite_devsite_cse_module.js"});v.set("devsite-device",{src:"/js/devsite_devsite_device_module.js"});v.set("devsite-dialog",{src:"/js/devsite_devsite_dialog_module.js"});
v.set("devsite-dynamic-content",{src:"/js/devsite_devsite_dynamic_content_module.js"});v.set("devsite-expandable",{src:"/js/devsite_devsite_expandable_module.js"});v.set("devsite-expandable-nav",{src:"/js/devsite_devsite_expandable_nav_module.js"});v.set("devsite-feedback",{src:"/js/devsite_devsite_feedback_module.js"});v.set("devsite-filter",{src:"/js/devsite_devsite_filter_module.js"});v.set("devsite-footer-linkboxes",{src:"/js/devsite_devsite_footer_linkboxes_module.js"});
v.set("devsite-footer-promos",{src:"/js/devsite_devsite_footer_promos_module.js"});v.set("devsite-footer-utility",{src:"/js/devsite_devsite_footer_utility_module.js"});v.set("devsite-forum",{src:"/js/devsite_devsite_forum_module.js"});v.set("devsite-google-survey",{src:"/js/devsite_devsite_google_survey_module.js"});v.set("devsite-googler-buttons",{src:"/js/devsite_devsite_googler_buttons_module.js"});v.set("devsite-hats-survey",{src:"/js/devsite_devsite_hats_survey_module.js"});
v.set("devsite-header",{src:"/js/devsite_devsite_header_module.js"});v.set("devsite-heading-link",{src:"/js/devsite_devsite_heading_link_module.js"});v.set("devsite-iframe",{src:"/js/devsite_devsite_iframe_module.js"});v.set("devsite-jump-to",{src:"/js/devsite_devsite_jump_to_module.js"});v.set("devsite-jsfiddle-button",{src:"/js/devsite_devsite_jsfiddle_button_module.js"});v.set("devsite-language-selector",{src:"/js/devsite_devsite_language_selector_module.js"});v.set("devsite-lightbox",{src:"/js/devsite_devsite_lightbox_module.js"});
v.set("devsite-mathjax",{src:"/js/devsite_devsite_mathjax_module.js"});v.set("devsite-mdc",{src:"/js/devsite_devsite_mdc_module.js"});v.set("devsite-multiple-choice",{src:"/js/devsite_devsite_multiple_choice_module.js"});v.set("devsite-nav-buttons",{src:"/js/devsite_devsite_nav_buttons_module.js"});v.set("devsite-playlist",{src:"/js/devsite_devsite_playlist_module.js"});v.set("devsite-page-rating",{src:"/js/devsite_devsite_page_rating_module.js"});v.set("devsite-pagination",{src:"/js/devsite_devsite_pagination_module.js"});
v.set("devsite-progress",{src:"/js/devsite_devsite_progress_module.js"});v.set("devsite-quiz",{src:"/js/devsite_devsite_quiz_module.js"});v.set("devsite-reference-results",{src:"/js/devsite_devsite_reference_results_module.js"});v.set("devsite-search",{src:"/js/devsite_devsite_search_module.js"});v.set("devsite-select",{src:"/js/devsite_devsite_select_module.js"});v.set("devsite-selector",{src:"/js/devsite_devsite_selector_module.js"});v.set("devsite-significatio",{src:"/js/devsite_devsite_significatio_module.js"});
v.set("devsite-sitemask",{src:"/js/devsite_devsite_sitemask_module.js"});v.set("devsite-snackbar",{src:"/js/devsite_devsite_snackbar_module.js"});v.set("devsite-sort",{src:"/js/devsite_devsite_sort_module.js"});v.set("devsite-spinner",{src:"/js/devsite_devsite_spinner_module.js"});v.set("devsite-support-form",{src:"/js/devsite_devsite_support_form_module.js"});v.set("devsite-tabs",{src:"/js/devsite_devsite_tabs_module.js"});v.set("devsite-thumb-rating",{src:"/js/devsite_devsite_thumb_rating_module.js"});
v.set("devsite-toc",{src:"/js/devsite_devsite_toc_module.js"});v.set("devsite-topic",{src:"/js/devsite_devsite_topic_module.js"});v.set("devsite-tooltip",{src:"/js/devsite_devsite_tooltip_module.js"});v.set("devsite-tracking-question",{src:"/js/devsite_devsite_tracking_question_module.js"});v.set("devsite-user",{src:"/js/devsite_devsite_user_module.js"});v.set("devsite-var",{src:"/js/devsite_devsite_var_module.js"});v.set("devsite-version-selector",{src:"/js/devsite_devsite_version_selector_module.js"});
v.set("devsite-vplus",{src:"/js/devsite_devsite_vplus_module.js"});v.set("devsite-wall-acknowledgement",{src:"/js/devsite_devsite_wall_acknowledgement_module.js"});v.set("devsite-youtube",{src:"/js/devsite_devsite_youtube_module.js"});v.set("google-codelab",{src:"/js/devsite_google_codelab_module.js"});v.set("google-codelab-about",{src:"/js/devsite_google_codelab_about_module.js"});v.set("google-codelab-analytics",{src:"/js/devsite_google_codelab_analytics_module.js"});
v.set("google-codelab-step",{src:"/js/devsite_google_codelab_step_module.js"});v.set("google-codelab-survey",{src:"/js/devsite_google_codelab_survey_module.js"});u("DevsiteAppAuthorizedElements",v);u("DevsiteAppTenantCustomized",!1);var Ba=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ca=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},Da=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,g=0;g<c;g++)g in e&&(d[g]=b.call(void 0,e[g],g,a));return d};function Ea(a){return Array.prototype.concat.apply([],arguments)}function Fa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ga(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};function Ha(a){if(8192>=a.length)return String.fromCharCode.apply(null,a);for(var b="",c=0;c<a.length;c+=8192)b+=String.fromCharCode.apply(null,Ga(a,c,c+8192));return b};function Ia(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ja(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};var Ka=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function w(a,b){return-1!=a.indexOf(b)}function La(a,b){return a<b?-1:a>b?1:0};var x;a:{var Ma=t.navigator;if(Ma){var Pa=Ma.userAgent;if(Pa){x=Pa;break a}}x=""};var y=0,z=0;function Qa(a){var b=a>>>0;a=Math.floor((a-b)/4294967296)>>>0;y=b;z=a}function A(a){var b=0>a;a=Math.abs(a);var c=a>>>0;a=Math.floor((a-c)/4294967296);a>>>=0;b&&(a=~a>>>0,c=(~c>>>0)+1,4294967295<c&&(c=0,a++,4294967295<a&&(a=0)));y=c;z=a}function Ra(a){var b=0>a;a=2*Math.abs(a);Qa(a);a=y;var c=z;b&&(0==a?0==c?c=a=4294967295:(c--,a=4294967295):a--);y=a;z=c}
function Sa(a){var b=0>a?1:0;a=b?-a:a;if(0===a)0<1/a?y=z=0:(z=0,y=2147483648);else if(isNaN(a))z=0,y=2147483647;else if(3.4028234663852886E38<a)z=0,y=(b<<31|2139095040)>>>0;else if(1.1754943508222875E-38>a)a=Math.round(a/Math.pow(2,-149)),z=0,y=(b<<31|a)>>>0;else{var c=Math.floor(Math.log(a)/Math.LN2);a*=Math.pow(2,-c);a=Math.round(8388608*a)&8388607;z=0;y=(b<<31|c+127<<23|a)>>>0}}
function Ta(a){var b=a.charCodeAt(4),c=a.charCodeAt(5),d=a.charCodeAt(6),e=a.charCodeAt(7);y=a.charCodeAt(0)+(a.charCodeAt(1)<<8)+(a.charCodeAt(2)<<16)+(a.charCodeAt(3)<<24)>>>0;z=b+(c<<8)+(d<<16)+(e<<24)>>>0}function Ua(a,b,c){var d=b>>31;c(a<<1^d,(b<<1|a>>>31)^d)}
function Va(a){function b(h,k){for(var l=0;8>l&&(1!==h||0<k);l++)k=h*e[l]+k,e[l]=k&255,k>>>=8}function c(){for(var h=0;8>h;h++)e[h]=~e[h]&255}var d=!1;"-"===a[0]&&(d=!0,a=a.slice(1));for(var e=[0,0,0,0,0,0,0,0],g=0;g<a.length;g++)b(10,a.charCodeAt(g)-48);d&&(c(),b(1,1));return Ha(e)};function B(a,b){this.a=a;this.b=b}function Wa(a){return new B((a.a>>>1|(a.b&1)<<31)>>>0,a.b>>>1>>>0)}function Xa(a){return new B(a.a<<1>>>0,(a.b<<1|a.a>>>31)>>>0)}f=B.prototype;f.Va=function(){return!!(this.a&1)};f.add=function(a){return new B((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};f.sub=function(a){return new B((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};
function Ya(a){var b=a&65535,c=a>>>16;a=10*b+65536*(0*b&65535)+65536*(10*c&65535);for(b=0*c+(0*b>>>16)+(10*c>>>16);4294967296<=a;)a-=4294967296,b+=1;return new B(a>>>0,b>>>0)}f.toString=function(){for(var a="",b=this;0!=b.a||0!=b.b;){var c=new B(0,0);b=new B(b.a,b.b);for(var d=new B(10,0),e=new B(1,0);!(d.b&2147483648);)d=Xa(d),e=Xa(e);for(;0!=e.a||0!=e.b;)0>=(d.b<b.b||d.b==b.b&&d.a<b.a?-1:d.b==b.b&&d.a==b.a?0:1)&&(c=c.add(e),b=b.sub(d)),d=Wa(d),e=Wa(e);c=[c,b];b=c[0];a=c[1].a+a}""==a&&(a="0");return a};
function Za(a){for(var b=new B(0,0),c=new B(0,0),d=0;d<a.length;d++){if("0">a[d]||"9"<a[d])return null;c.a=parseInt(a[d],10);var e=Ya(b.a);b=Ya(b.b);b.b=b.a;b.a=0;b=e.add(b).add(c)}return b}f.Na=function(){return new B(this.a,this.b)};function C(a,b){this.a=a;this.b=b}C.prototype.add=function(a){return new C((this.a+a.a&4294967295)>>>0>>>0,((this.b+a.b&4294967295)>>>0)+(4294967296<=this.a+a.a?1:0)>>>0)};
C.prototype.sub=function(a){return new C((this.a-a.a&4294967295)>>>0>>>0,((this.b-a.b&4294967295)>>>0)-(0>this.a-a.a?1:0)>>>0)};C.prototype.c=function(){return new C(this.a,this.b)};C.prototype.toString=function(){var a=0!=(this.b&2147483648),b=new B(this.a,this.b);a&&(b=(new B(0,0)).sub(b));return(a?"-":"")+b.toString()};function $a(a){var b=0<a.length&&"-"==a[0];b&&(a=a.substring(1));a=Za(a);if(null===a)return null;b&&(a=(new B(0,0)).sub(a));return new C(a.a,a.b)};function ab(){this.a=[]}f=ab.prototype;f.length=function(){return this.a.length};function bb(a){var b=a.a;a.a=[];return b}function D(a,b,c){for(;0<c||127<b;)a.a.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.a.push(b)}function E(a,b,c){F(a,b);F(a,c)}function cb(a,b,c){Ua(b,c,function(d,e){D(a,d>>>0,e>>>0)})}function G(a,b){for(;127<b;)a.a.push(b&127|128),b>>>=7;a.a.push(b)}function J(a,b){if(0<=b)G(a,b);else{for(var c=0;9>c;c++)a.a.push(b&127|128),b>>=7;a.a.push(1)}}
function db(a,b){G(a,(b<<1^b>>31)>>>0)}function eb(a,b){Ta(Va(b));Ua(y,z,function(c,d){D(a,c>>>0,d>>>0)})}f.Fc=function(a){this.a.push(a>>>0&255)};f.Ec=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};function F(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}function fb(a,b){Qa(b);F(a,y);F(a,z)}f.Bb=function(a){this.a.push(a>>>0&255)};f.Ab=function(a){this.a.push(a>>>0&255);this.a.push(a>>>8&255)};
function gb(a,b){a.a.push(b>>>0&255);a.a.push(b>>>8&255);a.a.push(b>>>16&255);a.a.push(b>>>24&255)}
function hb(a,b){var c=b;c=(b=0>c?1:0)?-c:c;if(0===c)z=0<1/c?0:2147483648,y=0;else if(isNaN(c))z=2147483647,y=4294967295;else if(1.7976931348623157E308<c)z=(b<<31|2146435072)>>>0,y=0;else if(2.2250738585072014E-308>c)c/=Math.pow(2,-1074),z=(b<<31|c/4294967296)>>>0,y=c>>>0;else{var d=c,e=0;if(2<=d)for(;2<=d&&1023>e;)e++,d/=2;else for(;1>d&&-1022<e;)d*=2,e--;c*=Math.pow(2,-e);z=(b<<31|e+1023<<20|1048576*c&1048575)>>>0;y=4503599627370496*c>>>0}F(a,y);F(a,z)}
f.Ma=function(a){this.a.push.apply(this.a,a)};function ib(a){ib[" "](a);return a}ib[" "]=ua;var jb=w(x,"Opera"),K=w(x,"Trident")||w(x,"MSIE"),kb=w(x,"Edge"),lb=w(x,"Gecko")&&!(w(x.toLowerCase(),"webkit")&&!w(x,"Edge"))&&!(w(x,"Trident")||w(x,"MSIE"))&&!w(x,"Edge"),mb=w(x.toLowerCase(),"webkit")&&!w(x,"Edge"),nb=w(x,"Macintosh");function ob(){var a=t.document;return a?a.documentMode:void 0}var pb;
a:{var qb="",rb=function(){var a=x;if(lb)return/rv:([^\);]+)(\)|;)/.exec(a);if(kb)return/Edge\/([\d\.]+)/.exec(a);if(K)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(mb)return/WebKit\/(\S+)/.exec(a);if(jb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();rb&&(qb=rb?rb[1]:"");if(K){var sb=ob();if(null!=sb&&sb>parseFloat(qb)){pb=String(sb);break a}}pb=qb}var tb=pb,ub={},vb;if(t.document&&K){var wb=ob();vb=wb?wb:parseInt(tb,10)||void 0}else vb=void 0;var xb=vb;var yb={},zb=null;function Ab(a,b){void 0===b&&(b=0);Bb();b=yb[b];for(var c=[],d=0;d<a.length;d+=3){var e=a[d],g=d+1<a.length,h=g?a[d+1]:0,k=d+2<a.length,l=k?a[d+2]:0,m=e>>2;e=(e&3)<<4|h>>4;h=(h&15)<<2|l>>6;l&=63;k||(l=64,g||(h=64));c.push(b[m],b[e],b[h]||"",b[l]||"")}return c.join("")}function Cb(a){var b=a.length,c=3*b/4;c%3?c=Math.floor(c):w("=.",a[b-1])&&(c=w("=.",a[b-2])?c-2:c-1);var d=new Uint8Array(c),e=0;Db(a,function(g){d[e++]=g});return d.subarray(0,e)}
function Db(a,b){function c(l){for(;d<a.length;){var m=a.charAt(d++),p=zb[m];if(null!=p)return p;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}Bb();for(var d=0;;){var e=c(-1),g=c(0),h=c(64),k=c(64);if(64===k&&-1===e)break;b(e<<2|g>>4);64!=h&&(b(g<<4&240|h>>2),64!=k&&b(h<<6&192|k))}}
function Bb(){if(!zb){zb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));yb[c]=d;for(var e=0;e<d.length;e++){var g=d[e];void 0===zb[g]&&(zb[g]=e)}}}};function Eb(){this.c=[];this.b=0;this.a=new ab;this.f=[]}function Fb(a,b){var c=bb(a.a);a.c.push(c);a.c.push(b);a.b+=c.length+b.length}function L(a,b){M(a,b,2);b=bb(a.a);a.c.push(b);a.b+=b.length;b.push(a.b);return b}function N(a,b){var c=b.pop();for(c=a.b+a.a.length()-c;127<c;)b.push(c&127|128),c>>>=7,a.b++;b.push(c);a.b++}f=Eb.prototype;f.Xa=function(a,b,c){null!=a&&null!=b&&null!=c&&Fb(this,a.subarray(b,c))};f.Ya=function(){this.c=[];bb(this.a);this.b=0;this.f=[]};
function Gb(a){for(var b=new Uint8Array(a.b+a.a.length()),c=a.c,d=c.length,e=0,g=0;g<d;g++){var h=c[g];b.set(h,e);e+=h.length}c=bb(a.a);b.set(c,e);a.c=[b];return b}f.ma=function(a){return Ab(Gb(this),a)};f.X=function(a){this.f.push(L(this,a))};f.ba=function(){N(this,this.f.pop())};function M(a,b,c){G(a.a,8*b+c)}
f.yb=function(a,b,c){switch(a){case 1:null!=c&&(M(this,b,1),hb(this.a,c));break;case 2:null!=c&&(M(this,b,5),a=this.a,Sa(c),F(a,y));break;case 3:null!=c&&null!=c&&(M(this,b,0),a=this.a,A(c),D(a,y,z));break;case 4:null!=c&&null!=c&&(M(this,b,0),a=this.a,A(c),D(a,y,z));break;case 5:null!=c&&Hb(this,b,c);break;case 6:null!=c&&(M(this,b,1),fb(this.a,c));break;case 7:null!=c&&(M(this,b,5),F(this.a,c));break;case 8:Ib(this,b,c);break;case 9:O(this,b,c);break;case 12:Jb(this,b,c);break;case 13:null!=c&&
Kb(this,b,c);break;case 14:Lb(this,b,c);break;case 15:null!=c&&(M(this,b,5),gb(this.a,c));break;case 16:null!=c&&(M(this,b,1),a=this.a,A(c),E(a,y,z));break;case 17:null!=c&&null!=c&&(M(this,b,0),db(this.a,c));break;case 18:null!=c&&null!=c&&(M(this,b,0),a=this.a,Ra(c),D(a,y,z))}};function Kb(a,b,c){null!=c&&(M(a,b,0),G(a.a,c))}function Hb(a,b,c){null!=c&&(M(a,b,0),J(a.a,c))}f.Dc=function(a,b){null!=b&&null!=b&&(M(this,a,0),eb(this.a,b))};function Ib(a,b,c){null!=c&&(M(a,b,0),a.a.a.push(c?1:0))}
function Lb(a,b,c){null!=c&&(c=parseInt(c,10),M(a,b,0),J(a.a,c))}
function O(a,b,c){if(null!=c){b=L(a,b);for(var d=a.a,e=0;e<c.length;e++){var g=c.charCodeAt(e);if(128>g)d.a.push(g);else if(2048>g)d.a.push(g>>6|192),d.a.push(g&63|128);else if(65536>g)if(55296<=g&&56319>=g&&e+1<c.length){var h=c.charCodeAt(e+1);56320<=h&&57343>=h&&(g=1024*(g-55296)+h-56320+65536,d.a.push(g>>18|240),d.a.push(g>>12&63|128),d.a.push(g>>6&63|128),d.a.push(g&63|128),e++)}else d.a.push(g>>12|224),d.a.push(g>>6&63|128),d.a.push(g&63|128)}N(a,b)}}
function Jb(a,b,c){null!=c&&(c=c.constructor===Uint8Array?c:c.constructor===ArrayBuffer?new Uint8Array(c):c.constructor===Array?new Uint8Array(c):c.constructor===String?Cb(c):new Uint8Array(0),M(a,b,2),G(a.a,c.length),Fb(a,c))}f.Cb=function(a,b,c){null!=b&&(a=L(this,a),c(b,this),N(this,a))};f.Db=function(a,b,c){null!=b&&(M(this,1,3),M(this,2,0),J(this.a,a),a=L(this,3),c(b,this),N(this,a),M(this,1,4))};f.zb=function(a,b,c){null!=b&&(M(this,a,3),c(b,this),M(this,a,4))};
f.lc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Hb(this,a,b[c])};f.mc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Hb(this,a,parseInt(d,10))}};f.nc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,0);var e=this.a;A(d);D(e,y,z)}}};f.wc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);M(this,a,1);E(this.a,g,h)}};
f.xc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);M(this,a,0);D(this.a,g,h)}};f.yc=function(a,b,c,d){if(null!=b)for(var e=0;e<b.length;e++){var g=c(b[e]),h=d(b[e]);M(this,a,0);cb(this.a,g>>>0,h>>>0)}};f.oc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=$a(e),M(this,d,0),D(this.a,e.a,e.b))}};f.zc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Kb(this,a,b[c])};
f.Ac=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&Kb(this,a,parseInt(d,10))}};f.Bc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,0);var e=this.a;A(d);D(e,y,z)}}};f.Cc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Za(e),M(this,d,0),D(this.a,e.a,e.b))}};f.tc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,0),db(this.a,d))}};
f.uc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,0);var e=this.a;Ra(d);D(e,y,z)}}};f.vc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,0),eb(this.a,d))}};f.fc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,5),F(this.a,d))}};f.hc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,1),fb(this.a,d))}};
f.ic=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=Za(e),M(this,d,1),E(this.a,e.a,e.b))}};f.qc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,5),gb(this.a,d))}};f.rc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,1);var e=this.a;A(d);E(e,y,z)}}};f.sc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=a,e=b[c];null!=e&&(e=$a(e),M(this,d,1),E(this.a,e.a,e.b))}};
f.jc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];if(null!=d){M(this,a,5);var e=this.a;Sa(d);F(e,y)}}};f.dc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++){var d=b[c];null!=d&&(M(this,a,1),hb(this.a,d))}};f.bc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Ib(this,a,b[c])};f.ec=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Lb(this,a,b[c])};function Mb(a,b,c){if(null!=c)for(var d=0;d<c.length;d++)O(a,b,c[d])}
f.cc=function(a,b){if(null!=b)for(var c=0;c<b.length;c++)Jb(this,a,b[c])};f.pc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++){var e=L(this,a);c(b[d],this);N(this,e)}};f.kc=function(a,b,c){if(null!=b)for(var d=0;d<b.length;d++)M(this,a,3),c(b[d],this),M(this,a,4)};f.Lb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)J(this.a,b[c]);N(this,a)}};f.Mb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)J(this.a,parseInt(b[c],10));N(this,a)}};
f.Nb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=this.a;A(b[c]);D(d,y,z)}N(this,a)}};f.Vb=function(a,b,c,d){if(null!=b){a=L(this,a);for(var e=0;e<b.length;e++)E(this.a,c(b[e]),d(b[e]));N(this,a)}};f.Wb=function(a,b,c,d){if(null!=b){a=L(this,a);for(var e=0;e<b.length;e++)D(this.a,c(b[e]),d(b[e]));N(this,a)}};f.Xb=function(a,b,c,d){if(null!=b){a=L(this,a);for(var e=this.a,g=0;g<b.length;g++)cb(e,c(b[g]),d(b[g]));N(this,a)}};
f.Ob=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=$a(b[c]);D(this.a,d.a,d.b)}N(this,a)}};f.Yb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)G(this.a,b[c]);N(this,a)}};f.Zb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)G(this.a,parseInt(b[c],10));N(this,a)}};f.$b=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=this.a;A(b[c]);D(d,y,z)}N(this,a)}};
f.ac=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=Za(b[c]);D(this.a,d.a,d.b)}N(this,a)}};f.Sb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)db(this.a,b[c]);N(this,a)}};f.Tb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++){var d=this.a;Ra(b[c]);D(d,y,z)}N(this,a)}};f.Ub=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)eb(this.a,b[c]);N(this,a)}};
f.Hb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,4*b.length),a=0;a<b.length;a++)F(this.a,b[a])};f.Ib=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,8*b.length),a=0;a<b.length;a++)fb(this.a,b[a])};f.Jb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,8*b.length),a=0;a<b.length;a++){var c=Za(b[a]);E(this.a,c.a,c.b)}};f.Pb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,4*b.length),a=0;a<b.length;a++)gb(this.a,b[a])};
f.Qb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;A(b[a]);E(c,y,z)}};f.Rb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,8*b.length),a=0;a<b.length;a++){var c=this.a;Ta(Va(b[a]));E(c,y,z)}};f.Kb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,4*b.length),a=0;a<b.length;a++){var c=this.a;Sa(b[a]);F(c,y)}};f.Fb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,8*b.length),a=0;a<b.length;a++)hb(this.a,b[a])};
f.Eb=function(a,b){if(null!=b&&b.length)for(M(this,a,2),G(this.a,b.length),a=0;a<b.length;a++)this.a.a.push(b[a]?1:0)};f.Gb=function(a,b){if(null!=b&&b.length){a=L(this,a);for(var c=0;c<b.length;c++)J(this.a,b[c]);N(this,a)}};function Nb(){}var Ob="function"==typeof Uint8Array;Nb.prototype.j=function(){return this.h};var Pb=[];function Qb(a){var b=a.f+a.g;a.a[b]||(a.b=a.a[b]={})}function P(a,b){if(b<a.f){b+=a.g;var c=a.a[b];return c===Pb?a.a[b]=[]:c}if(a.b)return c=a.b[b],c===Pb?a.b[b]=[]:c}function Q(a,b,c){a=P(a,b);return null==a?c:a}function R(a,b){a=P(a,b);a=null==a?a:!!a;return null==a?!1:a}function Rb(a,b,c){b<a.f?a.a[b+a.g]=c:(Qb(a),a.b[b]=c);return a}
function T(a,b,c,d){c!==d?Rb(a,b,c):b<a.f?a.a[b+a.g]=null:(Qb(a),delete a.b[b]);return a}function Sb(a,b,c,d){b=P(a,b);void 0!=d?b.splice(d,0,c):b.push(c);return a}f=Nb.prototype;f.sb=function(){if(this.c)for(var a in this.c){var b=this.c[a];if(Array.isArray(b))for(var c=0;c<b.length;c++);}};
f.P=Ob?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){return Ab(this)};try{return JSON.stringify(this.a&&this.a,Tb)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.a&&this.a,Tb)};function Tb(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)}f.toString=function(){return this.a.toString()};
f.$a=function(a){Qb(this);this.c||(this.c={});var b=a.c;return a.f?a.a()?(this.c[b]||(this.c[b]=Da(this.b[b]||[],function(c){return new a.b(c)})),this.c[b]):this.b[b]=this.b[b]||[]:a.a()?(!this.c[b]&&this.b[b]&&(this.c[b]=new a.b(this.b[b])),this.c[b]):this.b[b]};f.fb=function(a,b){this.c||(this.c={});Qb(this);var c=a.c;a.f?(b=b||[],a.a()?(this.c[c]=b,this.b[c]=Da(b,function(d){return d.a})):this.b[c]=b):a.a()?(this.c[c]=b,this.b[c]=b?b.a:b):this.b[c]=b;return this};f.aa=function(){return new this.constructor(Ub(this.a))};
f.Za=function(){return new this.constructor(Ub(this.a))};function Ub(a){if(Array.isArray(a)){for(var b=Array(a.length),c=0;c<a.length;c++){var d=a[c];null!=d&&(b[c]="object"==typeof d?Ub(d):d)}return b}if(Ob&&a instanceof Uint8Array)return new Uint8Array(a);b={};for(c in a)d=a[c],null!=d&&(b[c]="object"==typeof d?Ub(d):d);return b};function Vb(a){var b=a;a=Wb;this.c=null;b||(b=[]);this.h=void 0;this.g=-1;this.a=b;a:{if(b=this.a.length){--b;var c=this.a[b];if(!(null===c||"object"!=typeof c||Array.isArray(c)||Ob&&c instanceof Uint8Array)){this.f=b- -1;this.b=c;break a}}this.f=Number.MAX_VALUE}this.i={};if(a)for(b=0;b<a.length;b++)c=a[b],c<this.f?(c+=-1,this.a[c]=this.a[c]||Pb):(Qb(this),this.b[c]=this.b[c]||Pb)}Aa(Vb,Nb);var Wb=[10,12];f=Vb.prototype;
f.ab=function(a){var b,c={tb:Q(this,1,0),locale:Q(this,2,""),V:Q(this,4,""),oa:Q(this,5,""),ub:Q(this,6,""),Ha:Q(this,7,""),Ja:R(this,8),Ia:R(this,9),Y:null==(b=P(this,10))?void 0:b,Ka:R(this,11),rb:null==(b=P(this,12))?void 0:b};a&&(c.S=this);return c};
f.cb=function(){var a=new Eb;var b=this.getTenantId();0!==b&&Lb(a,1,b);b=this.getLocale();0<b.length&&O(a,2,b);b=Q(this,4,"");0<b.length&&O(a,4,b);b=Q(this,5,"");0<b.length&&O(a,5,b);b=Q(this,6,"");0<b.length&&O(a,6,b);b=this.getInsecureHost();0<b.length&&O(a,7,b);(b=R(this,8))&&Ib(a,8,b);(b=R(this,9))&&Ib(a,9,b);b=P(this,10);0<b.length&&Mb(a,10,b);(b=R(this,11))&&Ib(a,11,b);b=P(this,12);0<b.length&&Mb(a,12,b);return Gb(a)};f.getTenantId=function(){return Q(this,1,0)};
f.pb=function(a){return T(this,1,a,0)};f.getLocale=function(){return Q(this,2,"")};f.eb=function(a){return T(this,4,a,"")};f.hb=function(a){return T(this,5,a,"")};f.qb=function(a){return T(this,6,a,"")};f.getInsecureHost=function(){return Q(this,7,"")};f.ib=function(a){return T(this,7,a,"")};f.kb=function(a){return T(this,8,a,!1)};f.jb=function(a){return T(this,9,a,!1)};f.T=function(a,b){return Sb(this,10,a,b)};f.Z=function(){return Rb(this,10,[])};f.lb=function(a){return T(this,11,a,!1)};
f.U=function(a,b){return Sb(this,12,a,b)};f.$=function(){return Rb(this,12,[])};function Xb(){var a=GoogleDevelopersObject;return new Vb(a?JSON.parse(a):null)};var Yb="StopIteration"in t?t.StopIteration:{message:"StopIteration",stack:""};function Zb(){}Zb.prototype.next=function(){throw Yb;};Zb.prototype.a=function(){return this};function $b(a,b){this.b={};this.a=[];this.f=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof $b)for(c=a.s(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])}f=$b.prototype;f.m=function(){U(this);for(var a=[],b=0;b<this.a.length;b++)a.push(this.b[this.a[b]]);return a};f.s=function(){U(this);return this.a.concat()};
f.Da=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b];if(V(this.b,c)&&this.b[c]==a)return!0}return!1};f.da=function(a,b){if(this===a)return!0;if(this.c!=a.c)return!1;b=b||ac;U(this);for(var c,d=0;c=this.a[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};function ac(a,b){return a===b}f.Ea=function(){return 0==this.c};f.Ca=function(){this.b={};this.f=this.c=this.a.length=0};
function U(a){if(a.c!=a.a.length){for(var b=0,c=0;b<a.a.length;){var d=a.a[b];V(a.b,d)&&(a.a[c++]=d);b++}a.a.length=c}if(a.c!=a.a.length){var e={};for(c=b=0;b<a.a.length;)d=a.a[b],V(e,d)||(a.a[c++]=d,e[d]=1),b++;a.a.length=c}}f.get=function(a,b){return V(this.b,a)?this.b[a]:b};f.set=function(a,b){V(this.b,a)||(this.c++,this.a.push(a),this.f++);this.b[a]=b};f.forEach=function(a,b){for(var c=this.s(),d=0;d<c.length;d++){var e=c[d],g=this.get(e);a.call(b,g,e,this)}};
f.vb=function(){for(var a=new $b,b=0;b<this.a.length;b++){var c=this.a[b];a.set(this.b[c],c)}return a};f.Fa=function(){U(this);for(var a={},b=0;b<this.a.length;b++){var c=this.a[b];a[c]=this.b[c]}return a};f.ia=function(){return bc(this,!0)};f.na=function(){return bc(this,!1)};function bc(a,b){U(a);var c=0,d=a.f,e=new Zb;e.next=function(){if(d!=a.f)throw Error("The map has changed since the iterator was created");if(c>=a.a.length)throw Yb;var g=a.a[c++];return b?g:a.b[g]};return e}
function V(a,b){return Object.prototype.hasOwnProperty.call(a,b)};function cc(a){if(a.m&&"function"==typeof a.m)return a.m();if("string"===typeof a)return a.split("");if(wa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function dc(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(wa(a)||"string"===typeof a)Ca(a,b,c);else{if(a.s&&"function"==typeof a.s)var d=a.s();else if(a.m&&"function"==typeof a.m)d=void 0;else if(wa(a)||"string"===typeof a){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g)}else for(g in d=[],e=0,a)d[e++]=g;e=cc(a);g=e.length;for(var h=0;h<g;h++)b.call(c,e[h],d&&d[h],a)}};var ec=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^\\/?#]*)@)?([^\\/?#]*?)(?::([0-9]+))?(?=[\\/?#]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/;function fc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var g=a[c].substring(0,d);e=a[c].substring(d+1)}else g=a[c];b(g,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function gc(a,b){this.b=this.j=this.h="";this.f=null;this.i=this.c="";this.g=this.v=!1;if(a instanceof gc){this.g=void 0!==b?b:a.g;hc(this,a.h);var c=a.j;W(this);this.j=c;c=a.b;W(this);this.b=c;ic(this,a.f);c=a.c;W(this);this.c=c;jc(this,kc(a.a));a=a.i;W(this);this.i=a}else a&&(c=String(a).match(ec))?(this.g=!!b,hc(this,c[1]||"",!0),a=c[2]||"",W(this),this.j=lc(a),a=c[3]||"",W(this),this.b=lc(a,!0),ic(this,c[4]),a=c[5]||"",W(this),this.c=lc(a,!0),jc(this,c[6]||"",!0),a=c[7]||"",W(this),this.i=lc(a)):
(this.g=!!b,this.a=new mc(null,this.g))}f=gc.prototype;f.toString=function(){var a=[],b=this.h;b&&a.push(nc(b,oc,!0),":");var c=this.b;if(c||"file"==b)a.push("//"),(b=this.j)&&a.push(nc(b,oc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.f,null!=c&&a.push(":",String(c));if(c=this.c)this.b&&"/"!=c.charAt(0)&&a.push("/"),a.push(nc(c,"/"==c.charAt(0)?pc:qc,!0));(c=this.a.toString())&&a.push("?",c);(c=this.i)&&a.push("#",nc(c,rc));return a.join("")};
f.resolve=function(a){var b=new gc(this),c=!!a.h;c?hc(b,a.h):c=!!a.j;if(c){var d=a.j;W(b);b.j=d}else c=!!a.b;c?(d=a.b,W(b),b.b=d):c=null!=a.f;d=a.c;if(c)ic(b,a.f);else if(c=!!a.c){if("/"!=d.charAt(0))if(this.b&&!this.c)d="/"+d;else{var e=b.c.lastIndexOf("/");-1!=e&&(d=b.c.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(w(e,"./")||w(e,"/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var g=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&g.push(""):".."==k?((1<g.length||1==g.length&&
""!=g[0])&&g.pop(),d&&h==e.length&&g.push("")):(g.push(k),d=!0)}d=g.join("/")}else d=e}c?(W(b),b.c=d):c=""!==a.a.toString();c?jc(b,kc(a.a)):c=!!a.i;c&&(a=a.i,W(b),b.i=a);return b};function hc(a,b,c){W(a);a.h=c?lc(b,!0):b;a.h&&(a.h=a.h.replace(/:$/,""))}function ic(a,b){W(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.f=b}else a.f=null}function jc(a,b,c){W(a);b instanceof mc?(a.a=b,sc(a.a,a.g)):(c||(b=nc(b,tc)),a.a=new mc(b,a.g));return a}
f.nb=function(a,b){return jc(this,a,b)};f.ga=function(){return lc(this.a.toString())};f.ua=function(){return this.a.toString()};f.mb=function(a,b){W(this);Array.isArray(b)||(b=[String(b)]);uc(this.a,a,b);return this};f.la=function(a){return this.a.m(a)};f.ka=function(a){return this.a.get(a)};f.Ga=function(a){return(!this.b&&!a.b||this.b==a.b)&&(null==this.f&&null==a.f||this.f==a.f)};
f.Wa=function(){W(this);var a=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^za()).toString(36);W(this);this.a.set("zx",a);return this};f.va=function(a){W(this);vc(this.a,a);return this};f.ob=function(a){this.v=a;return this};f.La=function(){return this.v};function W(a){if(a.v)throw Error("Tried to modify a read-only Uri");}f.wa=function(a){this.g=a;this.a&&sc(this.a,a);return this};function wc(a){return a instanceof gc?new gc(a):new gc(a,void 0)}
function lc(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}function nc(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,xc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function xc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var oc=/[#\/\?@]/g,qc=/[#\?:]/g,pc=/[#\?]/g,tc=/[#\?@]/g,rc=/#/g;function mc(a,b){this.b=this.a=null;this.c=a||null;this.f=!!b}
function X(a){a.a||(a.a=new $b,a.b=0,a.c&&fc(a.c,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}f=mc.prototype;f.sa=function(){X(this);return this.b};f.add=function(a,b){X(this);this.c=null;a=yc(this,a);var c=this.a.get(a);c||this.a.set(a,c=[]);c.push(b);this.b+=1;return this};function vc(a,b){X(a);b=yc(a,b);V(a.a.b,b)&&(a.c=null,a.b-=a.a.get(b).length,a=a.a,V(a.b,b)&&(delete a.b[b],a.c--,a.f++,a.a.length>2*a.c&&U(a)))}f.pa=function(){this.a=this.c=null;this.b=0};
f.ta=function(){X(this);return 0==this.b};function zc(a,b){X(a);b=yc(a,b);return V(a.a.b,b)}f.qa=function(a){var b=this.m();return 0<=Ba(b,a)};f.forEach=function(a,b){X(this);this.a.forEach(function(c,d){Ca(c,function(e){a.call(b,e,d,this)},this)},this)};f.s=function(){X(this);for(var a=this.a.m(),b=this.a.s(),c=[],d=0;d<b.length;d++)for(var e=a[d],g=0;g<e.length;g++)c.push(b[d]);return c};
f.m=function(a){X(this);var b=[];if("string"===typeof a)zc(this,a)&&(b=Ea(b,this.a.get(yc(this,a))));else{a=this.a.m();for(var c=0;c<a.length;c++)b=Ea(b,a[c])}return b};f.set=function(a,b){X(this);this.c=null;a=yc(this,a);zc(this,a)&&(this.b-=this.a.get(a).length);this.a.set(a,[b]);this.b+=1;return this};f.get=function(a,b){if(!a)return b;a=this.m(a);return 0<a.length?String(a[0]):b};function uc(a,b,c){vc(a,b);0<c.length&&(a.c=null,a.a.set(yc(a,b),Fa(c)),a.b+=c.length)}
f.toString=function(){if(this.c)return this.c;if(!this.a)return"";for(var a=[],b=this.a.s(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.m(d);for(var g=0;g<d.length;g++){var h=e;""!==d[g]&&(h+="="+encodeURIComponent(String(d[g])));a.push(h)}}return this.c=a.join("&")};f.ea=function(a){X(this);this.a.forEach(function(b,c){0<=Ba(a,c)||vc(this,c)},this);return this};function kc(a){var b=new mc;b.c=a.c;a.a&&(b.a=new $b(a.a),b.b=a.b);return b}
function yc(a,b){b=String(b);a.f&&(b=b.toLowerCase());return b}function sc(a,b){b&&!a.f&&(X(a),a.c=null,a.a.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(vc(this,d),uc(this,e,c))},a));a.f=b}f.ra=function(a){for(var b=0;b<arguments.length;b++)dc(arguments[b],function(c,d){this.add(d,c)},this)};var Ac={};function Bc(a,b){var c=Ac[a];if(void 0!==c&&(!c.K||Date.now()<=c.K+3E5))return c.p;c=new Promise(function(e,g){b.onload=function(){return e(b)};b.onerror=function(h){b.parentNode&&b.parentNode.removeChild(b);g(h)};document.head.appendChild(b)});var d={K:0,p:c};c.catch(function(){return d.K=+new Date});Ac[a]=d;return c}function Cc(a){var b=void 0===b?null:b;a=wc(a);var c=document.createElement("script");c.src=a.toString();b&&(c.type=b);return Bc(a.toString(),c)};var Dc=!K||9<=Number(xb),Ec=!K||9<=Number(xb),Fc;
if(Fc=K){var Gc;if(Object.prototype.hasOwnProperty.call(ub,"9"))Gc=ub["9"];else{for(var Hc=0,Ic=Ka(String(tb)).split("."),Jc=Ka("9").split("."),Kc=Math.max(Ic.length,Jc.length),Lc=0;0==Hc&&Lc<Kc;Lc++){var Mc=Ic[Lc]||"",Nc=Jc[Lc]||"";do{var Oc=/(\d*)(\D*)(.*)/.exec(Mc)||["","","",""],Pc=/(\d*)(\D*)(.*)/.exec(Nc)||["","","",""];if(0==Oc[0].length&&0==Pc[0].length)break;Hc=La(0==Oc[1].length?0:parseInt(Oc[1],10),0==Pc[1].length?0:parseInt(Pc[1],10))||La(0==Oc[2].length,0==Pc[2].length)||La(Oc[2],Pc[2]);
Mc=Oc[3];Nc=Pc[3]}while(0==Hc)}Gc=ub["9"]=0<=Hc}Fc=!Gc}var Qc=Fc,Rc=function(){if(!t.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{t.addEventListener("test",ua,b),t.removeEventListener("test",ua,b)}catch(c){}return a}();function Sc(){this.A=this.A;this.b=this.b}f=Sc.prototype;f.A=!1;f.R=function(){return this.A};f.ha=Sc.prototype.R;f.G=function(){this.A||(this.A=!0,this.H())};f.bb=function(a){a=ya(Tc,a);this.A?a():(this.b||(this.b=[]),this.b.push(a))};f.H=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Tc(a){a&&"function"==typeof a.G&&a.G()};function Uc(a,b){this.type=a;this.b=this.target=b;this.J=this.f=!1}Uc.prototype.g=function(){this.f=!0};Uc.prototype.c=function(){this.J=!0};function Y(a,b){Uc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.v=this.j=0;this.key="";this.h=this.i=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.I=null;this.L=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(lb){a:{try{ib(b.nodeName);
var e=!0;break a}catch(g){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.j=mb||void 0!==a.offsetX?a.offsetX:a.layerX,this.v=mb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.i=a.keyCode||0;this.key=a.key||"";this.h=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.L=nb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Vc[a.pointerType]||"";this.I=a.state;this.a=a;a.defaultPrevented&&this.c()}}Aa(Y,Uc);var Wc=[1,4,2],Vc={2:"touch",3:"pen",4:"mouse"};
Y.prototype.wb=function(){return(Dc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Wc[0]))&&!(nb&&this.ctrlKey)};Y.prototype.g=function(){Y.M.g.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};Y.prototype.c=function(){Y.M.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Qc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Xc="closure_listenable_"+(1E6*Math.random()|0),Yc=0;function Zc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Yc;this.B=this.F=!1}function $c(a){a.B=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function ad(a){this.src=a;this.a={};this.b=0}f=ad.prototype;f.ya=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};f.add=function(a,b,c,d,e){var g=a.toString();a=this.a[g];a||(a=this.a[g]=[],this.b++);var h=bd(a,b,d,e);-1<h?(b=a[h],c||(b.F=!1)):(b=new Zc(b,this.src,g,!!d,e),b.F=c,a.push(b));return b};
f.Aa=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=bd(e,b,c,d);return-1<b?($c(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};f.Ba=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,$c(d[e]);delete this.a[c];this.b--}return b};f.ja=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
f.za=function(a,b){var c=void 0!==a,d=c?a.toString():"",e=void 0!==b;return Ja(this.a,function(g){for(var h=0;h<g.length;++h)if(!(c&&g[h].type!=d||e&&g[h].capture!=b))return!0;return!1})};function bd(a,b,c,d){for(var e=0;e<a.length;++e){var g=a[e];if(!g.B&&g.listener==b&&g.capture==!!c&&g.b==d)return e}return-1};var cd="closure_lm_"+(1E6*Math.random()|0),dd={},ed=0;function fd(a,b,c,d,e){if(d&&d.once)return gd(a,b,c,d,e);if(Array.isArray(b)){for(var g=0;g<b.length;g++)fd(a,b[g],c,d,e);return null}c=hd(c);return a&&a[Xc]?a.b(b,c,xa(d)?!!d.capture:!!d,e):id(a,b,c,!1,d,e)}
function id(a,b,c,d,e,g){if(!b)throw Error("Invalid event type");var h=xa(e)?!!e.capture:!!e,k=jd(a);k||(a[cd]=k=new ad(a));c=k.add(b,c,d,h,g);if(c.a)return c;d=kd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Rc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(ld(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");ed++;return c}
function kd(){var a=md,b=Ec?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function gd(a,b,c,d,e){if(Array.isArray(b)){for(var g=0;g<b.length;g++)gd(a,b[g],c,d,e);return null}c=hd(c);return a&&a[Xc]?a.c(b,c,xa(d)?!!d.capture:!!d,e):id(a,b,c,!0,d,e)}
function nd(a){if("number"!==typeof a&&a&&!a.B){var b=a.src;if(b&&b[Xc])b.f(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(ld(c),d):b.addListener&&b.removeListener&&b.removeListener(d);ed--;if(c=jd(b)){d=a.type;if(d in c.a){var e=c.a[d],g=Ba(e,a),h;(h=0<=g)&&Array.prototype.splice.call(e,g,1);h&&($c(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[cd]=null)}else $c(a)}}}
function ld(a){return a in dd?dd[a]:dd[a]="on"+a}function od(a,b,c,d){var e=!0;if(a=jd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.B&&(g=pd(g,d),e=e&&!1!==g)}return e}function pd(a,b){var c=a.listener,d=a.b||a.src;a.F&&nd(a);return c.call(d,b)}
function md(a,b){if(a.B)return!0;if(!Ec){if(!b)a:{b=["window","event"];for(var c=t,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new Y(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.f&&0<=e;e--){b.b=d[e];var g=od(d[e],a,!0,b);c=c&&g}for(e=0;!b.f&&e<d.length;e++)b.b=d[e],g=od(d[e],a,!1,b),c=
c&&g}return c}return pd(a,new Y(b,this))}function jd(a){a=a[cd];return a instanceof ad?a:null}var qd="__closure_events_fn_"+(1E9*Math.random()>>>0);function hd(a){if("function"==va(a))return a;a[qd]||(a[qd]=function(b){return a.handleEvent(b)});return a[qd]};function rd(a){Sc.call(this);this.c=a;this.a={}}Aa(rd,Sc);var sd=[];f=rd.prototype;f.Sa=function(a,b,c,d,e){return td(this,a,b,c,d,e)};function td(a,b,c,d,e,g){Array.isArray(c)||(c&&(sd[0]=c.toString()),c=sd);for(var h=0;h<c.length;h++){var k=fd(b,c[h],d||a.handleEvent,e||!1,g||a.c||a);if(!k)break;a.a[k.key]=k}return a}function ud(a,b){vd(Z.b,a,"devsite-content-updated",b,void 0)}f.Ra=function(a,b,c,d,e){return vd(this,a,b,c,d,e)};
function vd(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)vd(a,b,c[h],d,e,g);else{b=gd(b,c,d||a.handleEvent,e,g||a.c||a);if(!b)return a;a.a[b.key]=b}return a}f.Ta=function(a,b,c,d){b.a(a,c,d,this.c||this,this);return this};f.Ua=function(a,b,c,d,e){b.a(a,c,d,e||this.c||this,this);return this};f.xa=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function wd(a,b,c,d,e,g){if(Array.isArray(c))for(var h=0;h<c.length;h++)wd(a,b,c[h],d,e,g);else d=d||a.handleEvent,e=xa(e)?!!e.capture:!!e,g=g||a.c||a,d=hd(d),e=!!e,b&&b[Xc]?c=b.a(c,d,e,g):b?(b=jd(b))?(c=b.a[c.toString()],b=-1,c&&(b=bd(c,d,e,g)),c=-1<b?c[b]:null):c=null:c=null,c&&(nd(c),delete a.a[c.key])}f.xb=function(a,b,c,d,e){b.b(a,c,d,e||this.c||this,this);return this};function xd(a){Ia(a.a,function(b,c){this.a.hasOwnProperty(c)&&nd(b)},a);a.a={}}f.H=function(){rd.M.H.call(this);xd(this)};
f.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function yd(){var a=this;if(t.__globalAppLoader)return t.__globalAppLoader;this.c=null;this.h=!1;this.b=new rd;this.f=[];this.g=function(b){a.f.push(b)};try{this.a=Xb()}catch(b){zd("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;u("__globalAppLoader",this)}yd.prototype.G=function(){xd(this.b)};
function Ad(a){var b=[];b.push(Cc("https://www.gstatic.com/external_hosted/polymer/v2/webcomponents-lite.js"));"fetch"in window&&"URL"in window||b.push(Cc(Q(a.a,5,"")+"/js/polyfills.js"));return Promise.all(b)}
function Bd(){var a=Cd,b,c,d,e,g,h,k;return ta(new sa(new oa(function(l){switch(l.a){case 1:return K&&document.body.setAttribute("ie-"+parseInt(tb,10),""),l.c=2,q(l,Ad(a),4);case 4:la(l,3);break;case 2:b=ma(l),zd("Failed to load Devsite App dependencies: "+b.message);case 3:c=new Promise(function(m){u("__devsiteAppReadyResolver",m)});u("__devsiteAppReadyPromise",c);u("DevsiteApp.whenReady",function(){return c});if(!P(a.a,12).length){l.u(5);break}l.c=6;return q(l,Promise.all(P(a.a,12).map(function(m){m=
wc(m);var p=document.createElement("link");p.setAttribute("rel","stylesheet");p.setAttribute("type","text/css");p.setAttribute("href",m.toString());return Bc(m.toString(),p)})),8);case 8:la(l,5);break;case 6:d=ma(l),zd("Failed to load Devsite App dependencies: "+d.message);case 5:return e=t.DevsiteAppTenantCustomized?Q(a.a,6,""):Q(a.a,5,""),l.c=9,q(l,Cc(e+(a.a.getLocale()&&"en"!=a.a.getLocale()?Q(a.a,4,"").replace(/\.js$/,"__"+a.a.getLocale().toLowerCase().replace("-","_")+".js"):Q(a.a,4,""))),11);
case 11:la(l,10);break;case 9:g=ma(l);if("en"===a.a.getLocale()){zd("Failed to load Devsite App binary: "+g.message);l.u(10);break}T(a.a,2,"en","");l.c=13;return q(l,Cc(e+Q(a.a,4,"")),15);case 15:la(l,10);break;case 13:h=ma(l),zd("Failed to load Devsite App binary: "+h.message);case 10:if(k=document,"complete"===k.readyState||"interactive"===k.readyState)l.u(0);else return q(l,new Promise(function(m){k.addEventListener("readystatechange",function(){"interactive"!==k.readyState&&"complete"!==k.readyState||
m()})}),0)}})))}function zd(a){throw new function(b){this.message=b;this.name="DevsiteAppLoaderException"}(void 0===a?"Devsite has failed to load.":a);};var Z=new yd;(function(){var a=document.querySelector("devsite-content");a&&(td(Z.b,window,"message",Z.g,void 0),ud(a,function(){wd(Z.b,window,"message",Z.g);for(var b=n(Z.f),c=b.next();!c.done;c=b.next())window.dispatchEvent(c.value.a);Z.f=[]}))})();var Dd;var Cd=Z;"WeakMap"in window&&"performance"in window&&"now"in window.performance?(Cd.c||(Cd.c=Bd()),Dd=Cd.c):Dd=Promise.resolve();
Dd.then(function(){t.DevsiteAppInit||zd("Failed to load Devsite App binary");R(Z.a,9)?DevsiteAppFrameboxInit(Z.a.P(),t.DevsiteAppAuthorizedElements):DevsiteAppInit(Z.a.P(),t.DevsiteAppAuthorizedElements)});}).call(this);
