(function(_ds){var window=this;'use strict';var dQ=function(a){var b=a.Oo,c=a.tm,d=a.bl;a=a.Lm;var e='<ul class="devsite-nav-list" scrollbars><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle"><a href="#top_of_page" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Contents</span></a>';c&&(e=e+'<button type="button" title="'+_ds.Hl("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";for(var g=b.length,k=0;k<g;k++){var m=b[k];e+=
'<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.V(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.V(k)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.V(k)+'" track-metadata-link-destination="#'+_ds.V(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.U(m.text)+"</span></a>";if(_ds.yl(m.children).length){e+=
'<ul class="devsite-nav-list">';m=m.children;for(var n=m.length,q=0;q<n;q++){var r=m[q];e+='<li class="devsite-nav-item"'+(c&&r.index<a?" visible":"")+'><a href="#'+_ds.V(r.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.V(k)+"."+_ds.V(q)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.V(k)+"."+_ds.V(q)+'" track-metadata-link-destination="#'+
_ds.V(r.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.U(r.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.Hl("Expand/collapse contents"),e+='" aria-hidden="true"></button></li>');return(0,_ds.T)(e+"</ul>")},fQ=function(){var a=_ds.S.call(this)||this;a.h=!1;a.C=!1;a.G=new _ds.Aj;a.L=[];a.M=0;a.D=[];a.J=new _ds.xj(function(){return eQ(a)},16);a.m=null;a.F=new _ds.Rp;a.o=new Set;a.H=[];a.j=null;return a},hQ=function(a){var b,c,d;_ds.E(function(e){switch(e.h){case 1:if(!("IntersectionObserver"in _ds.Id())){e.K(2);break}a.m&&a.m.disconnect();b=document.querySelector("devsite-header");c=152;if(!b){e.K(3);
break}return _ds.v(e,window.customElements.whenDefined("devsite-header"),4);case 4:(d=parseFloat(b.getAttribute("top-row--height")||0)+parseFloat(b.getAttribute("bottom-row--height")||0))&&(c=d);case 3:a.m=new IntersectionObserver(function(g){gQ(a,g)},{rootMargin:c+"px 0px 0px 0px",threshold:[0,1]});case 2:a.F.resolve(),_ds.x(e)}})},iQ=function(a){_ds.Mg(a);a.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));a.removeAttribute("visible");a.setAttribute("hidden","");a.h||(a=document.querySelector(".devsite-main-content"))&&
a.removeAttribute("has-toc")},jQ=function(a){a.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));a.removeAttribute("hidden");a.setAttribute("visible","");if(!a.h){var b=document.querySelector(".devsite-main-content");b&&b.setAttribute("has-toc","");hQ(a)}},eQ=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.h?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),kQ(a,b),a.C=!0,a.h||(lQ(a),mQ(a))):
iQ(a)}},kQ=function(a,b){var c,d,e,g;_ds.E(function(k){c=[];d=!1;e=Array.from(b.querySelectorAll("h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)")).filter(function(m){return m.id&&m.dataset.text}).filter(function(m){return nQ(m)});e.forEach(function(m,n){m={id:m.id,level:m.tagName.toLowerCase(),text:m.dataset.text,children:[],index:n};"h2"===m.level?(c.push(m),d=!0):d?c[c.length-1].children.push(m):c.push(m)});if((g=_ds.Hb(a.D,
c,a.kh.bind(a)))&&a.C)return k.return();c.length?(oQ(a,c),jQ(a),a.h||pQ(a,e)):iQ(a);a.D=c;a.h||(lQ(a),mQ(a),a.dispatchEvent(new CustomEvent("devsite-toc-updated",{bubbles:!0})));_ds.x(k)})},gQ=function(a,b){b=_ds.p(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting?a.o.add(c.target):a.o.delete(c.target);if(b=a.o.values().next().value){var d="#"+b.id,e="#"+encodeURI(b.id);b=a.H.find(function(g){g=g.href;return-1!==g.indexOf(d,g.length-d.length)||-1!==g.indexOf(e,g.length-e.length)});
a.j!==b&&(a.j&&a.j.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.j=b))}},pQ=function(a,b){var c,d,e;_ds.E(function(g){if(1==g.h)return _ds.v(g,a.F.h,2);if(!a.m)return g.return();a.m.disconnect();a.o.clear();a.j&&a.j.classList.remove("devsite-nav-active");a.j=null;c=_ds.p(b);for(d=c.next();!d.done;d=c.next())e=d.value,a.m.observe(e);_ds.x(g)})},nQ=function(a){return _ds.lv.find(function(b){return!!_ds.qh(a,b,6)})||_ds.ph(a,"devsite-selector",null,6)||_ds.qh(a,"devsite-dialog",
3)?!1:!0},oQ=function(a,b){var c=_ds.lm(dQ,{Oo:b,tm:a.h,bl:!!document.body.querySelector("devsite-apix, .devsite-apix"),Lm:5});a.H=Array.from(c.querySelectorAll(".devsite-nav-title"));_ds.Mg(a);a.h&&c.setAttribute("hidden","");a.appendChild(c);a.h&&(8<=a.getElementsByClassName("devsite-nav-item").length&&(Array.from(a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items")).forEach(function(d){a.G.listen(d,"click",function(){a.hasAttribute("expanded")?a.removeAttribute("expanded"):a.setAttribute("expanded",
"")})}),a.setAttribute("expandable","")),setTimeout(function(){c.removeAttribute("hidden")},0))},mQ=function(a){var b=a.getAttribute("offset")||0;(a=a.querySelector(".devsite-nav-list"))&&_ds.Jj(a,"transform","translate3d(0, -"+b+"px, 0)")},lQ=function(a){var b=a.getAttribute("max-height")||0;(a=a.querySelector(".devsite-nav-list"))&&_ds.Jj(a,"max-height",b+"px")};_ds.u(fQ,_ds.S);_ds.f=fQ.prototype;_ds.f.connectedCallback=function(){this.h=this.hasAttribute("devsite-toc-embedded");eQ(this)};_ds.f.disconnectedCallback=function(){iQ(this);this.C=!1;_ds.Gj(this.G)};_ds.f.attributeChangedCallback=function(a){switch(a){case "offset":mQ(this);break;case "max-height":lQ(this)}};_ds.f.updateContent=function(a){a=a&&"false"===a.toLowerCase();this.D=[];_ds.Mg(this);a?(this.setAttribute("disabled",""),iQ(this)):(this.removeAttribute("disabled"),jQ(this),this.J.oa())};
_ds.f.kh=function(a,b){var c=!0;if(a.children.length||b.children.length)c=_ds.Hb(a.children,b.children,this.kh.bind(this));return c&&a.id===b.id&&a.text===b.text};_ds.l.Object.defineProperties(fQ,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["max-height","offset"]}}});fQ.prototype.updateContent=fQ.prototype.updateContent;fQ.prototype.attributeChangedCallback=fQ.prototype.attributeChangedCallback;fQ.prototype.disconnectedCallback=fQ.prototype.disconnectedCallback;
fQ.prototype.connectedCallback=fQ.prototype.connectedCallback;try{window.customElements.define("devsite-toc",fQ)}catch(a){console.warn("devsite.app.customElement.DevsiteToc",a)};})(_ds_www);
