(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var oK=function(a,b){lK()&&(b=mK()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Jj(a,nK(),b))},rK=function(){var a=_ds.S.call(this)||this;a.G=-1;a.h=new _ds.Aj;a.H=new _ds.Aj;a.C=0;a.J=new MutationObserver(function(){return pK(a)});a.M=new _ds.xj(function(){pK(a);qK(a)},15);a.L=0;a.m=0;a.o=0;a.j=0;a.D=!1;return a},tK=function(a){a.h.listen(a,"devsite-search-toggle",function(b){b.ea.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active")});a.h.listen(document.body,
"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});a.h.listen(window,"resize",function(){return sK(a)});a.h.listen(document.body,["devsite-page-loaded","devsite-content-updated"],function(){sK(a)});a.h.listen(a,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!=b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",
{bubbles:!0})))})},sK=function(a){window.requestAnimationFrame(function(){return a.M.oa()})},uK=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},pK=function(a){a.L=uK(a,".devsite-top-logo-row-wrapper-wrapper");a.m=uK(a,".devsite-collapsible-section");a.o=uK(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",a.L);a.setAttribute("bottom-row--height",a.m);a.setAttribute("bottom-tabs--height",a.o);vK(a)},wK=function(a){if(!a.querySelector(".devsite-search-background")&&
(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity=1;a.appendChild(b)}},vK=function(a){var b=a.querySelector(".devsite-collapsible-section");a.j>=a.m&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.j<a.m-a.o&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.j!==a.G&&(_ds.Jj(b,"transform","translate3d(0, -"+a.j+"px, 0)"),qK(a),a.G=a.j)},
xK=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.Gj(a.H);a.C&&window.cancelAnimationFrame(a.C);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.mg(b.offsetWidth,b.offsetHeight);b=new _ds.mg(c.offsetWidth,c.offsetHeight);var g=_ds.ak(c,"margin"),k="rtl"===document.documentElement.getAttribute("dir")?1:-1,m=(e.width-g.left-g.right)/b.width;e=(e.width-
(b.width+g.left+g.right))*k;var n=(g=a.hasAttribute("search-active"))?e:0,q=g?m:1;_ds.Jj(d,{opacity:1,width:b.width+"px",height:b.height+"px"});oK(c,a.hasAttribute("search-active")?0:e);_ds.Ej(a.H,d,_ds.Xu,function(){var r=a.querySelector("devsite-search"),t=a.querySelector(".devsite-search-background");t&&(t.style.opacity=0);r&&(r.removeAttribute("transition"),oK(r,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.C=window.requestAnimationFrame(function(){c.setAttribute("transition",
"");if(lK()){var r=mK()?"scale3d("+q+",1,1)":"scale("+q+",1)";_ds.Jj(d,nK(),r)}oK(c,n)})}},qK=function(a){0===a.m?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},yK=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,
d.value)},zK=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.D=!0,_ds.ol(a,c,b))};var lK=_ds.Ob(function(){return!_ds.Dg||0<=_ds.zc(_ds.ew,9)}),mK=_ds.Ob(function(){return _ds.Fg||_ds.Lr||_ds.Lj&&0<=_ds.zc(_ds.ew,10)||_ds.Dg&&0<=_ds.zc(_ds.ew,10)}),nK=_ds.Ob(function(){return _ds.Dg&&9==_ds.Fe?"-ms-transform":"transform"});_ds.u(rK,_ds.S);rK.prototype.attributeChangedCallback=function(a){"offset"===a?(this.j=parseFloat(this.getAttribute("offset"))||0,vK(this)):"search-active"===a&&xK(this)};rK.prototype.connectedCallback=function(){tK(this);wK(this);qK(this);pK(this);this.J.observe(this,{childList:!0,subtree:!0});vK(this);var a=_ds.ji();this.F=_ds.$h(_ds.bi(a.href),"authuser")};rK.prototype.disconnectedCallback=function(){_ds.Gj(this.h);this.J.disconnect()};
rK.prototype.updateContent=function(a){this.D=!1;a=_ds.nl(a);zK(this,a,".devsite-header-upper-tabs");zK(this,a,".devsite-collapsible-section");zK(this,a,".devsite-product-name-wrapper");zK(this,a,"devsite-language-selector");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&yK(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(yK(c,b),c=_ds.ji(),c=_ds.$h(_ds.bi(c.href),"authuser"),c!==this.F&&(this.F=c,b.refresh()));_ds.ol(this,this.querySelector("cloudx-additional-tabs"),
a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.ol(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"));this.D||(_ds.Mg(this),this.appendChild(a));wK(this);sK(this)};_ds.l.Object.defineProperties(rK,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active"]}}});rK.prototype.updateContent=rK.prototype.updateContent;
rK.prototype.disconnectedCallback=rK.prototype.disconnectedCallback;rK.prototype.connectedCallback=rK.prototype.connectedCallback;rK.prototype.attributeChangedCallback=rK.prototype.attributeChangedCallback;try{window.customElements.define("devsite-header",rK)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
