(function(_ds){var window=this;'use strict';var MH=function(){var a=_ds.S.call(this)||this;a.o=new _ds.Aj;a.C=new _ds.Aj;a.j=new Set;a.h=null;"IntersectionObserver"in window&&(a.h=new IntersectionObserver(function(b){b=_ds.p(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.Hr(new _ds.Fr,c),a.j.delete(c),a.h.unobserve(c))},{rootMargin:"100%"}));return a},NH=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Ng(c,b);c.appendChild(b)}})},VH=function(a,b){var c,d,e,g,k,m,n;return _ds.E(function(q){if(1==q.h)return _ds.v(q,DevsiteApp.whenReady(),2);c=_ds.ji();d=DevsiteApp.getInsecureHost();e=b.ea;if(e.origin!==c.origin&&d&&e.origin!==d)return q.return();try{g=_ds.xf(_ds.rk,e.data)}catch(r){return q.return()}k=_ds.N(g,
1,0);if(4===k)return OH(a,e),q.return();m=g.getName();if(!m)return q.return();if(n=a.querySelector('devsite-iframe iframe[name="'+m+'"]'))switch(k){case 5:PH(g,n);break;case 8:QH(e,g,c);break;case 1:RH(e,g,c);break;case 6:case 7:SH(k,c,g);break;case 9:TH(a,g);break;case 10:UH(g,c)}_ds.x(q)})},PH=function(a,b){var c,d,e,g;_ds.E(function(k){c=_ds.Eg(document).y;d=_ds.N(a,4,0);e=_ds.N(a,3,0);g=_ds.Xg(b);d&&g.setAttribute("width",d+"px");e&&g.setAttribute("height",e+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.Eg(document).x,
c)});_ds.x(k)})},OH=function(a,b){var c,d,e;_ds.E(function(g){if(c=WH(a,b.source)){d="goog_"+_ds.Ck++;c.setAttribute("name",d);var k=_ds.sk(3);e=_ds.Q(k,2,d);(k=b.source)&&k.postMessage(e.Fa(),"*")}_ds.x(g)})},QH=function(a,b,c){var d;_ds.E(function(e){var g=_ds.tk(_ds.sk(8),_ds.N(b,8,""));d=_ds.Q(g,6,c.toString());(g=a.source)&&g.postMessage(d.Fa(),"*");_ds.x(e)})},RH=function(a,b,c){var d;_ds.E(function(e){var g=_ds.tk(_ds.sk(2),_ds.N(b,8,""));d=_ds.Q(g,7,c.search+c.hash);(g=a.source)&&g.postMessage(d.Fa(),
"*");_ds.x(e)})},SH=function(a,b,c){var d,e,g;_ds.E(function(k){d=c.Da();e=new URL(c.getUrl(),b.origin);g=window.location.origin+window.location.pathname+e.search+e.hash;6===a?window.history.pushState({},d,g):window.history.replaceState({},d,g);_ds.x(k)})},TH=function(a,b){var c,d,e,g;_ds.E(function(k){c=_ds.N(b,9,"");d=JSON.parse(_ds.N(b,10,""));"cloudtrackEvent"===c&&d?(e=d,g={eventData:e},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:g,bubbles:!0}))):"devsite-apix"===
c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.x(k)})},UH=function(a,b){var c,d;_ds.E(function(e){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.x(e)})},WH=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.ah(d)===b&&(c=d)});return c},ZH=function(a){a.m=a.querySelector(".devsite-article-body");
a.m&&XH(a);a.h&&a.h.disconnect();a.j.clear();NH(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, td > code, th > code"));a.j.clear();a.j=new Set(b);if(_ds.ji().hash){b=new _ds.Fr;for(var c=_ds.p(a.j),d=c.next();!d.done;d=c.next())_ds.Hr(b,d.value)}else YH(a,a.j);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},XH=function(a){"full"===document.body.getAttribute("layout")&&(a=a.m.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},YH=function(a,b){a.h&&b.forEach(function(c){a.h.observe(c)})};_ds.u(MH,_ds.S);MH.prototype.connectedCallback=function(){var a=this;this.o.listen(window,"message",function(b){return VH(a,b)});ZH(this)};MH.prototype.disconnectedCallback=function(){this.h&&this.h.disconnect();this.j.clear();_ds.Gj(this.o);_ds.Gj(this.C)};
MH.prototype.updateContent=function(a){var b=this;"string"===typeof a&&(a=_ds.nl(a));[".devsite-article","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.ol(b,b.querySelector(c),a.querySelector(c))});ZH(this)};MH.prototype.updateContent=MH.prototype.updateContent;MH.prototype.disconnectedCallback=MH.prototype.disconnectedCallback;MH.prototype.connectedCallback=MH.prototype.connectedCallback;try{window.customElements.define("devsite-content",MH)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
