(function(_ds){var window=this;'use strict';var LN=function(){return(0,_ds.T)('<div class="devsite-select"></div>')},MN=function(a){var b=a.Lc,c=a.If;a='<label id="'+_ds.V(a.id)+'-label" style="display:none;"'+(b?' aria-label="'+_ds.V(b)+'"':"")+">";return(0,_ds.T)((c?a+"Select one or more options":a+"Select an option")+"</label>")},NN=function(a){var b=a.label,c=a.If;a=a.id;return(0,_ds.T)('<button type="button" class="devsite-select-toggle" id="'+_ds.V(a)+'-button" aria-haspopup="listbox" aria-labelledby="'+_ds.V(a)+"-label "+
_ds.V(a)+'-button"'+(c?' aria-multiselectable="true"':"")+">"+_ds.U(b)+"</button>")},ON=function(a){var b=a.options;a=a.id;for(var c='<ul class="devsite-select-list" tabindex="-1" role="listbox" aria-expanded="false" scrollbars aria-labelledby="'+_ds.V(a)+'-button">',d=b.length,e=0;e<d;e++){var g=b[e];c+='<li role="option" id="'+_ds.V(a)+"-"+_ds.V(e)+'" class="devsite-select-item" data-index="'+_ds.V(e)+'"'+(g.defaultSelected?' data-selected aria-selected="true"':' aria-selected="false"')+' aria-label="'+
_ds.V(g.Lc)+'">'+_ds.U(g.label)+"</li>"}return(0,_ds.T)(c+"</ul>")},PN=function(){var a=_ds.S.call(this)||this;a.m=null;a.G=null;a.C=new _ds.Aj;a.D=new _ds.Aj;a.J=null;a.L=!1;a.o=!1;a.M="";a.h=null;a.F=null;a.j=null;a.H=null;a.O=new _ds.yj;return a},QN=function(a){var b=a.querySelector(".kd-select");b&&(b.classList.remove("kd-select"),Array.from(b.classList).forEach(function(c){a.classList.add(c);b.classList.remove(c)}))},UN=function(a){a.j=a.querySelector("select");var b;(b=a.j.id)||(RN++,b="devsite-select-"+
RN+Math.random().toString().substr(2));a.j&&(a.j.options.length&&(a.H=a.j.options),a.j.hasAttribute("multiple")&&(a.o=!0,a.classList.add("devsite-select--multiple")));if(a.H){var c=_ds.lm(LN),d=a.j.options;d=d[a.j.selectedIndex]||d[0];a.M=a.hasAttribute("label")?a.getAttribute("label"):d.label;d={Lc:a.j.getAttribute("aria-label"),id:b,If:a.o};d=_ds.lm(MN,d);c.appendChild(d);a.F=_ds.lm(NN,{label:a.M,If:a.o,id:b});c.appendChild(a.F);a.h=_ds.lm(ON,{options:Array.from(a.H).map(function(e){return{defaultSelected:e.defaultSelected,
Lc:SN(e.label,e.defaultSelected),label:e.label}}),id:b});c.appendChild(a.h);a.appendChild(c);TN(a)}a.L=!0},TN=function(a){a.C.listen(a.F,"click",function(b){clearTimeout(a.J);a.dispatchEvent(new CustomEvent("devsite-close-select",{bubbles:!0}));b.preventDefault();b.stopPropagation();a.hasAttribute("menu--open")?VN(a):WN(a)});a.C.listen(a.h,"click",function(b){b.target.classList.contains("devsite-select-item")&&XN(a,b.target)});a.C.listen(a.h,"focusout",function(){a.J=setTimeout(function(){return VN(a)},
200)});a.C.listen(a.j,"change",function(){YN(a,ZN(a.querySelectorAll("option")))});a.C.listen(a.h,"keydown",function(b){return void $N(a,b)});a.C.listen(a.F,"keydown",function(b){var c=b.which||b.keyCode;if(38===c||40===c)b.preventDefault(),WN(a),$N(a,b)})},$N=function(a,b){var c=b.which||b.keyCode;switch(c){case 38:case 40:b.preventDefault();if(a.m){if(b=40===c?_ds.Tg(a.m):_ds.Ug(a.m))a.m.classList.remove("devsite-focused"),a.h.setAttribute("aria-activedescendant",b.id),b.classList.add("devsite-focused"),
a.m=b}else aO(a);a.m.scrollIntoView({block:"nearest"});break;case 13:case 32:b.preventDefault();XN(a,a.m);break;case 9:case 27:VN(a)}},WN=function(a){a.setAttribute("menu--open","");a.setAttribute("aria-expanded","true");a.h.focus();a.m||aO(a)},VN=function(a){a.removeAttribute("menu--open");a.removeAttribute("aria-expanded");a.D.listen(document.body,"click",a.G);a.D.listen(document.body,"devsite-close-select",a.G)},XN=function(a,b){b&&(bO(a,parseInt(b.dataset.index,10)),a.o||VN(a),a.j.dispatchEvent(new Event("change")))},
aO=function(a){if(!a.m&&a.h&&a.h.children.length){var b=Array.from(a.h.children).find(function(c){return c.hasAttribute("data-selected")});a.m=b?b:a.h.children[0];a.h.setAttribute("aria-activedescendant",a.m.id)}},cO=function(a){a.G=function(b){if("devsite-close-select"!==b.type||b.target!==a)a.o&&"devsite-select-item"===b.target.className||VN(a)};a.h&&(a.D.listen(document.body,"click",a.G),a.D.listen(document.body,"devsite-close-select",a.G))},dO=function(a){if(a.h&&a.F){a.h.style.removeProperty("left");
a.h.style.removeProperty("right");var b=a.h.getBoundingClientRect();0<b.x+b.width-_ds.zj(a.O).width?a.h.style.right="0":a.h.style.left="0"}},ZN=function(a){return Array.from(a).reduce(function(b,c,d){c.selected&&b.push(d);return b},[])},bO=function(a,b){var c=a.querySelectorAll("option");if(c&&c.length){if(!a.o)for(var d=_ds.p(c),e=d.next();!e.done;e=d.next())e.value.removeAttribute("selected");c[b]&&(b=c[b],a.o&&b.hasAttribute("selected")?b.removeAttribute("selected"):b.setAttribute("selected","true"));
YN(a,ZN(c))}},YN=function(a,b){var c=a.querySelectorAll(".devsite-select-item");Array.from(c).forEach(function(d,e){d=!1;b.includes(e)?(d=!0,c[e].setAttribute("data-selected",""),c[e].setAttribute("aria-selected","true"),a.h.setAttribute("aria-activedescendant",c[e].id)):(c[e].removeAttribute("data-selected"),c[e].setAttribute("aria-selected","false"));c[e].setAttribute("aria-label",SN(c[e].textContent,d))});a.o||(a.F.textContent=a.j.options[b[0]].label);dO(a)},SN=function(a,b){return(void 0===b?
0:b)?a+", selected":a},RN=0;_ds.u(PN,_ds.S);
PN.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.E(function(e){if(1==e.h){if("menu--open"!==a||b===c)return e.K(2);if(!d.hasAttribute("menu--open"))return d.removeAttribute("menu--show"),_ds.Gj(d.D),e.K(2);dO(d);d.removeAttribute("menu-position");if(d.h){var g=d.h.getBoundingClientRect(),k=_ds.zj(d.O).height,m=parseInt(_ds.Nj(d.h,"maxHeight"),10);d.setAttribute("menu-position",g.top+(d.h.scrollHeight>m?m:d.h.scrollHeight)<k?"below":"above")}cO(d);return _ds.v(e,0,4)}2!=
e.h&&d.setAttribute("menu--show","");"reset"===a&&bO(d,0);_ds.x(e)})};PN.prototype.connectedCallback=function(){this.L||(QN(this),UN(this))};PN.prototype.disconnectedCallback=function(){_ds.Gj(this.D);_ds.Gj(this.C)};_ds.l.Object.defineProperties(PN,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["label","menu--open","reset"]}}});PN.prototype.disconnectedCallback=PN.prototype.disconnectedCallback;PN.prototype.connectedCallback=PN.prototype.connectedCallback;
PN.prototype.attributeChangedCallback=PN.prototype.attributeChangedCallback;try{window.customElements.define("devsite-select",PN)}catch(a){console.warn("devsite.app.customElement.DevsiteSelect",a)};})(_ds_www);
