(function(_ds){var window=this;'use strict';var ZM=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return ZM.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c},$M=function(a,b,c,d,e,g,k,m,n,q){this.h=a;this.C=b;this.H=c;this.m=d;this.o=e;this.D=g;this.F=k;this.G=m;this.j=n;this.J=q},aN=function(a){return new $M(a.m,a.o,a.G,a.h,a.j,a.C,a.J,a.F,a.D,a.H)},bN=function(a,b){a.H=b;return a},cN=function(a,b){a.D=b;return a},dN=function(a,b){a.F=b;return a},eN=function(){this.m=null;
this.o="";this.H=this.D=this.F=this.J=this.C=this.j=this.h=this.G=null},fN=function(a){var b=a.ea;b=(b=b&&"composed"in b&&b&&"composedPath"in b&&b.composed&&b.composedPath())&&0<b.length?b[0]:a.target;return aN(bN(cN(dN((new eN).keyCode(a.keyCode||0).key(a.key||"").shiftKey(!!a.shiftKey).altKey(!!a.altKey).ctrlKey(!!a.ctrlKey).metaKey(!!a.metaKey).target(a.target),b),function(){return a.preventDefault()}),function(){return a.stopPropagation()}))},gN=function(a){this.h=a||null;this.next=a?null:{}},
hN=function(a,b){var c=b.shift();(0,_ds.fd)(c,function(d){var e=a[d];e&&(0==b.length?e.h&&delete a[d]:e.next&&(hN(e.next,b.slice(0)),_ds.Tb(e.next)&&delete a[d]))})},kN=function(a){a=a.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();a=a.split(" ");for(var b=[],c,d=0;c=a[d];d++){var e=c.split("+"),g=null,k=null;c=0;for(var m,n=0;m=e[n];n++){switch(m){case "shift":c|=1;continue;case "ctrl":c|=2;continue;case "alt":c|=4;continue;case "meta":c|=8;continue}e=void 0;g=m;if(!iN){k={};for(e in jN)k[jN[e]]=
_ds.Kr(parseInt(e,10));iN=k}k=iN[g];g=m;break}b.push({key:g,keyCode:k,modifiers:c})}return b},lN=function(a,b,c){c=c||0;b=["c_"+b+"_"+c];""!=a&&b.push("n_"+a+"_"+c);return b},mN=function(a,b){if("string"===typeof b[a])a=(0,_ds.Jb)(kN(b[a]),function(e){return lN(e.key||"",e.keyCode,e.modifiers)});else{var c=b,d=a;Array.isArray(b[a])&&(c=b[a],d=0);for(a=[];d<c.length;d+=2)a.push(lN("",c[d],c[d+1]))}return a},nN=function(a,b){32==a.D&&32==b.h&&(0,b.j)();a.D=null},oN=function(a){return _ds.Du&&a.o&&a.m},
pN=function(a,b,c){var d=b.shift();(0,_ds.fd)(d,function(e){if((e=a[e])&&(0==b.length||e.h))throw Error("Keyboard shortcut conflicts with existing shortcut");});b.length?(0,_ds.fd)(d,function(e){e=e.toString();var g=new gN;e=e in a?a[e]:a[e]=g;pN(e.next,b.slice(0),c)}):(0,_ds.fd)(d,function(e){a[e]=new gN(c)})},qN=function(a,b){for(var c=0;c<b.length;c++){var d=a[b[c]];if(d)return d}},rN=function(a,b,c){for(;0<c.length&&b;){var d=c.shift();if((d=qN(b,d))&&(0==c.length&&d.h||rN(a,d.next,c.slice(0))))return!0}return!1},
sN=function(a,b,c){_ds.Gf.call(this,a,c);this.j=b},tN=function(a,b,c){a:{var d=b.h;if(""!=b.C){var e=b.C;if("Control"==e||"Shift"==e||"Meta"==e||"AltGraph"==e){d=!1;break a}}else if(16==d||17==d||18==d){d=!1;break a}e=b.G;var g="TEXTAREA"==e.tagName||"INPUT"==e.tagName||"BUTTON"==e.tagName||"SELECT"==e.tagName,k=!g&&(e.isContentEditable||e.ownerDocument&&"on"==e.ownerDocument.designMode);d=!g&&!k||a.L[d]||a.F?!0:k?!1:a.M&&(b.m||b.o||b.D)?!0:"INPUT"==e.tagName&&a.X[e.type]?13==d:"INPUT"==e.tagName||
"BUTTON"==e.tagName?a.O?!0:32!=d:!1}d&&(!c&&oN(b)?a.o=!1:(c=_ds.Kr(b.h),d=lN(b.C,c,(b.H?1:0)|(b.o?2:0)|(b.m?4:0)|(b.D?8:0)),(e=qN(a.m,d))&&(e=!(1500<=(0,_ds.Qd)()-a.C)),e||(a.m=a.j,a.C=(0,_ds.Qd)()),(e=qN(a.m,d))&&e.next&&(a.m=e.next,a.C=(0,_ds.Qd)()),e&&(e.next?(0,b.j)():(a.m=a.j,a.C=(0,_ds.Qd)(),a.H&&(0,b.j)(),a.J&&(0,b.J)(),d=e.h,e=a.dispatchEvent(new sN("shortcut",d,b.F)),(e&=a.dispatchEvent(new sN("shortcut_"+d,d,b.F)))||(0,b.j)(),_ds.Lj&&(a.D=c)))))},wN=function(a){_ds.Ni.call(this);this.m=
this.j={};this.C=0;this.L=ZM(uN);this.X=ZM(vN);this.H=!0;this.F=this.J=!1;this.M=!0;this.O=!1;this.D=null;this.h=a;_ds.Uf(this.h,"keydown",this.Ph,void 0,this);_ds.Uf(this.h,"synthetic-keydown",this.Uh,void 0,this);_ds.Du&&(_ds.Uf(this.h,"keypress",this.Wh,void 0,this),_ds.Uf(this.h,"synthetic-keypress",this.Xh,void 0,this));_ds.Uf(this.h,"keyup",this.Qh,void 0,this);_ds.Uf(this.h,"synthetic-keyup",this.Vh,void 0,this)},xN=function(){return(0,_ds.T)('<div class="devsite-popout"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide aria-haspopup="true"></div></div>')},
yN=function(a){a=a||{};var b='<button type="submit" class="button button-white devsite-search-project-scope">';a="All results in "+_ds.U(a.Va);return(0,_ds.T)(b+a+"</button>")},zN=function(a){var b=a.query,c=a.ic,d='<button type="submit" class="button button-white devsite-suggest-all-results">';a.Tb?(a="All results across "+_ds.U(c),d+=a):(a='All results for "'+(_ds.U(b)+'"'),d+=a);return(0,_ds.T)(d+"</button>")},AN=function(a){var b=a.title,c=a.public,d=a.lj,e=a.Va,g=a.Tb,k=a.Mf;a='<a class="devsite-result-item-link" href="'+
_ds.V(_ds.am(a.link))+'"><span class="devsite-suggestion-fragment">'+_ds.U(b)+"</span>"+(k?'<span class="devsite-suggestion-fragment">'+_ds.U(k)+"</span>":"")+(d?'<span class="devsite-suggestion-fragment">'+_ds.U(d)+"</span>":"")+(_ds.Al(e)&&!g?'<span class="devsite-suggestion-fragment">'+_ds.U(e)+"</span>":"");c||(a+='<span class="devsite-result-item-confidential">Confidential</span>');return(0,_ds.T)(a+"</a>")},BN=function(a){var b=a.Va,c=a.Tb,d=a.query,e=a.rj;a=a.ic;b='<div class="devsite-suggest-wrapper '+
(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">There are no suggestions for your query</div></div>'+((e?'<div class="devsite-suggest-footer">'+(c?yN({Va:b}):"")+zN({Tb:c,query:d,ic:a})+"</div>":"")+"</div>");return(0,_ds.T)(b)},CN=function(a){var b=a.yn,c=a.Hn,d=a.On,e=a.Va,g=a.Tb,k=a.query,m=a.Tn,n=a.rj;a=a.ic;var q='<div class="devsite-suggest-wrapper '+(n?"":"devsite-search-disabled")+'" tabindex="0" role="menu"><div class="devsite-suggest-section">';
if(0<d.length){q=q+'<div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading">Suggested searches'+((g?'<span class="devsite-suggest-project">'+_ds.U(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="menu" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');for(var r=d.length,t=0;t<r;t++){var w=d[t];q+='<div class="devsite-result-item devsite-nav-label" role="menuitem" index=":'+
_ds.V(t)+'">'+AN({link:_ds.N(w,2,""),title:w.Da(),public:!0})+"</div>"}q+="</devsite-analytics-scope>"}q+=0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){q=q+'<div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading">Pages'+((g?'<span class="devsite-suggest-project">'+_ds.U(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="menu" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');
r=b.length;for(t=0;t<r;t++)w=b[t],q+='<div class="devsite-result-item devsite-nav-label" role="menuitem" index=":'+_ds.V(t)+'">'+AN({link:_ds.N(w,2,""),title:w.Da(),public:!0,Va:_ds.N(w,4,""),Tb:g})+"</div>";q+="</devsite-analytics-scope>"}q+=0<m.length&&0<b.length+d.length?'<hr role="none">':"";if(0<m.length){q=q+'<div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading">Reference'+((g?'<span class="devsite-suggest-project">'+_ds.U(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="menu" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');
r=m.length;for(t=0;t<r;t++)w=m[t],q+='<div class="devsite-result-item devsite-nav-label" role="menuitem" index=":'+_ds.V(t)+'">'+AN({link:_ds.N(w,2,""),title:w.Da(),public:!0,lj:_ds.N(w,3,""),Va:_ds.N(w,4,""),Tb:g,Mf:_ds.M(w,10)[0]})+"</div>";q+="</devsite-analytics-scope>"}q+=0<c.length&&0<b.length+d.length+m.length?'<hr role="none">':"";if(0<c.length){q+='<div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading">Products</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="menu" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)m=c[d],q+='<div class="devsite-result-item devsite-nav-label" role="menuitem" index=":'+_ds.V(d)+'">'+AN({link:_ds.N(m,2,""),title:m.Da(),public:!0})+"</div>";q+="</devsite-analytics-scope>"}q+="</div>"+(n?'<div class="devsite-suggest-footer">'+(g?yN({Va:e}):"")+zN({Tb:g,query:k,ic:a})+"</div>":"")+"</div>";return(0,_ds.T)(q)},DN=function(){var a=_ds.S.call(this)||this;a.H=!1;a.F={};a.G="";a.C=null;a.j=new _ds.Aj;a.h=null;return a},IN=function(a){a.h&&(a.j.listen(a.h,"suggest-service-search",
function(b){a:{var c=a.D.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}EN(a,b.detail.originalEvent,!!a.C)}}),a.j.listen(a.h,"suggest-service-suggestions-received",function(b){return void FN(a,b)}),a.j.listen(a.h,"suggest-service-focus",function(){GN(a,!0)}),a.j.listen(a.h,"suggest-service-blur",function(){GN(a,!1)}),a.j.listen(a.h,"suggest-service-input",function(){!a.F["Text Entered Into Search Bar"]&&a.h.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.F["Text Entered Into Search Bar"]=!0)}),a.j.listen(a.h,"suggest-service-navigate",function(b){return void HN(a,b)}),a.j.listen(document.body,"devsite-page-changed",function(){return a.F={}}),a.h.wj("SLASH",191));a.m&&a.j.listen(a.m,"submit",function(b){EN(a,b)});a.D&&a.j.listen(a.D,"click",function(b){var c=b.target;"A"==c.tagName.toUpperCase()&&GN(a,!1);c.classList.contains("devsite-search-project-scope")&&
EN(a,b,!0)});a.M&&a.j.listen(a.M,"click",function(){return void GN(a,!0)});a.L&&a.j.listen(a.L,"click",function(){return void GN(a,!1)})},EN=function(a,b,c){c=void 0===c?!1:c;var d,e;_ds.E(function(g){if(1==g.h){b.preventDefault();b.stopPropagation();if(!a.hasAttribute("enable-search"))return g.K(0);a.F["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.F["Full Site Search"]=
!0);d=c&&a.C?_ds.qi(a.C):_ds.qi(a.m.getAttribute("action"));e=new _ds.Mh(d.href);_ds.Zh(e,"q",a.h.query);d.search=e.h.toString();return _ds.v(g,DevsiteApp.fetchPage(d.href),3)}GN(a,!1);_ds.x(g)})},HN=function(a,b){var c=b.detail;b=a.o.querySelector(".highlight");var d;a=Array.from(a.o.querySelectorAll(".devsite-result-item"));var e=[],g=-1;if(b){var k=_ds.oh(b,function(n){return n.classList.contains("devsite-suggest-section")});e=Array.from(k.querySelectorAll(".devsite-result-item"));k=_ds.Tg(b.parentNode.parentNode);
var m=_ds.Ug(b.parentNode.parentNode);g=a.indexOf(b)}switch(c.keyCode){case 37:if(!k&&!m)return;b&&(c=b.getAttribute("index"),m?(d=m.querySelector('[index="'+c+'"]'))||(d=_ds.yb(Array.from(m.querySelectorAll("[index]")))):k&&((d=k.querySelector('[index="'+c+'"]'))||(d=_ds.yb(Array.from(k.querySelectorAll("[index]"))))));break;case 39:if(!k&&!m)return;b&&(c=b.getAttribute("index"),k?(d=k.querySelector('[index="'+c+'"]'))||(d=_ds.yb(Array.from(k.querySelectorAll("[index]")))):m&&((d=m.querySelector('[index="'+
c+'"]'))||(d=_ds.yb(Array.from(m.querySelectorAll("[index]"))))));break;case 38:b?(d=a[g-1])||(d=_ds.yb(e)):d=_ds.yb(a);break;case 40:b?(d=a[g+1])||(d=e[0]):d=a[0]}b&&b.classList.remove("highlight");d&&(d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},GN=function(a,b){if(a.H!==b){_ds.st(a.h,b);if(a.H=b)a.setAttribute("search-active","");else{var c=a.D.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");
_ds.Mg(a.o)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},FN=function(a,b){b=b.detail;var c=b.suggestions;b=b.query;if(a.h.query.toLowerCase().startsWith(b.toLowerCase()))if(c){var d=c.kb();c=d.filter(function(y){return 2===y.Nb()});var e=d.filter(function(y){return 3===y.Nb()}),g=d.filter(function(y){return 4===y.Nb()}).slice(0,5),k=d.filter(function(y){return 1===y.Nb()});d=c.length+g.length+k.length;var m=a.C?a.C:"";g.forEach(function(y){return y.yc(_ds.qi(m+
"/s/results/?q="+y.Da()).toString())});var n=b.split(JN);e.forEach(function(y){return _ds.jt(y,_ds.M(y,10).filter(function(A){return n.some(function(z){return A.includes(z)})}))});var q=a.getAttribute("project-name")||"",r=a.hasAttribute("project-scope"),t=a.hasAttribute("enable-search"),w=a.getAttribute("tenant-name")||"";c={yn:c,Va:q,Tb:r,Hn:k,On:g,query:b,Tn:e,rj:t,ic:w};0===d?_ds.im(a.o,BN,c):(_ds.im(a.o,CN,c),KN(a,b));a.o.removeAttribute("hidden")}else a.o.setAttribute("hidden","")},KN=function(a,
b){Array.from(a.o.querySelectorAll(".devsite-suggestion-fragment")).forEach(function(c){var d=_ds.lh(c);d=d.replace(new RegExp("("+b+")","ig"),"<b>$1</b>");d=_ds.mt(d);_ds.Dd(c,d)})},jN={8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"caps-lock",27:"esc",32:"space",33:"pg-up",34:"pg-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",59:"semicolon",61:"equals",65:"a",
66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",93:"context",96:"num-0",97:"num-1",98:"num-2",99:"num-3",100:"num-4",101:"num-5",102:"num-6",103:"num-7",104:"num-8",105:"num-9",106:"num-multiply",107:"num-plus",109:"num-minus",110:"num-period",111:"num-division",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",
186:"semicolon",187:"equals",189:"dash",188:",",190:".",191:"/",192:"`",219:"open-square-bracket",220:"\\",221:"close-square-bracket",222:"single-quote",224:"win"};_ds.f=eN.prototype;_ds.f.keyCode=function(a){this.m=a;return this};_ds.f.key=function(a){this.o=a;return this};_ds.f.shiftKey=function(a){this.G=a;return this};_ds.f.altKey=function(a){this.h=a;return this};_ds.f.ctrlKey=function(a){this.j=a;return this};_ds.f.metaKey=function(a){this.C=a;return this};
_ds.f.target=function(a){this.J=a;return this};var uN=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],vN="color date datetime datetime-local email month number password search tel text time url week".split(" "),iN;_ds.G(sN,_ds.Gf);_ds.G(wN,_ds.Ni);_ds.f=wN.prototype;_ds.f.VB=function(){return this.H};_ds.f.Gaa=function(a){this.J=a};_ds.f.WB=function(){return this.J};_ds.f.Daa=function(a){this.F=a};_ds.f.RB=function(){return this.F};_ds.f.Oda=function(a){this.M=a};_ds.f.RF=function(){return this.M};
_ds.f.Faa=function(a){this.O=a};_ds.f.mj=_ds.ca(4);_ds.f.fha=function(a){hN(this.j,mN(0,arguments))};_ds.f.ZS=function(a){return rN(this,this.j,mN(0,arguments))};_ds.f.Cca=function(a){this.L=ZM(a)};_ds.f.nE=function(){return _ds.Sb(this.L)};
_ds.f.$=function(){wN.va.$.call(this);this.j={};_ds.eg(this.h,"keydown",this.Ph,!1,this);_ds.eg(this.h,"synthetic-keydown",this.Uh,!1,this);_ds.Du&&(_ds.eg(this.h,"keypress",this.Wh,!1,this),_ds.eg(this.h,"synthetic-keypress",this.Xh,!1,this));_ds.eg(this.h,"keyup",this.Qh,!1,this);_ds.eg(this.h,"synthetic-keyup",this.Vh,!1,this);this.h=null};_ds.f.fK=function(a){return"shortcut_"+a};_ds.f.Qh=function(a){a=fN(a);_ds.Lj&&nN(this,a);_ds.Du&&!this.o&&oN(a)&&tN(this,a,!0)};
_ds.f.Vh=function(a){a=a.j();_ds.Lj&&nN(this,a);_ds.Du&&!this.o&&oN(a)&&tN(this,a,!0)};_ds.f.Wh=function(a){a=fN(a);32<a.h&&oN(a)&&(this.o=!0)};_ds.f.Xh=function(a){a=a.j();32<a.h&&oN(a)&&(this.o=!0)};_ds.f.Ph=function(a){tN(this,fN(a))};_ds.f.Uh=function(a){tN(this,a.j())};
_ds.tt.prototype.wj=_ds.da(5,function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=this;this.h&&this.h.dispose();a&&(this.h=new wN(document),this.h.H=!1,this.h.mj.apply(this.h,[a].concat(_ds.oa(c))),this.eventHandler.listen(this.h,"shortcut",function(g){var k=document;k.activeElement&&k.activeElement===k.body&&(g.preventDefault(),_ds.st(e,!0))}))});wN.prototype.mj=_ds.da(4,function(a,b){pN(this.j,mN(1,arguments),a)});var JN=/[ .()<>{}\[\]\/:,]+/;_ds.u(DN,_ds.S);DN.prototype.disconnectedCallback=function(){_ds.Gj(this.j);this.h&&(this.h.dispose(),this.h=null)};DN.prototype.attributeChangedCallback=function(a,b,c){"project-scope"==a&&(this.G=c||"",this.h&&(this.h.L=this.G));"url-scoped"==a&&(this.C=c)};
DN.prototype.connectedCallback=function(){if(this.m=this.querySelector("form"))this.J=this.m.querySelector(".devsite-search-query"),this.M=this.m.querySelector(".devsite-search-button[search-open]"),this.L=this.querySelector(".devsite-search-button[search-close]"),this.D=_ds.lm(xN),this.o=this.D.querySelector(".devsite-suggest-results-container"),this.m.appendChild(this.D),this.hasAttribute("project-scope")&&(this.G=this.getAttribute("project-scope")),this.hasAttribute("url-scoped")&&(this.C=this.getAttribute("url-scoped")),
this.m&&this.J&&(this.h=new _ds.tt(this.m,this.J),this.h.j=!0,this.h.gf=this.hasAttribute("enable-query-completion"),this.h.Yd=!0,this.h.ef=!0,this.h.hf=!0,this.h.L=this.G,this.h.j=this.hasAttribute("enable-suggestions")),IN(this)};_ds.l.Object.defineProperties(DN,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["project-scope","url-scoped"]}}});DN.prototype.connectedCallback=DN.prototype.connectedCallback;DN.prototype.attributeChangedCallback=DN.prototype.attributeChangedCallback;
DN.prototype.disconnectedCallback=DN.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",DN)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
