(function(_ds){var window=this;'use strict';var zH=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.kb(d)){var e=a.length||0,g=d.length||0;a.length=e+g;for(var k=0;k<g;k++)a[e+k]=d[k]}else a.push(d)}},AH=function(){var a=new _ds.hr;zH(a.L,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},BH=function(){var a=AH();(0,_ds.fd)(["devsite-var"],function(b){this.J.push(b)},a);return a},CH=function(){return(0,_ds.T)('<div class="devsite-code-buttons-container"></div>')},
DH=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.V(a)+'" data-title="'+_ds.V(a)+'"></button>')},EH=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+
_ds.V(a)+'" data-title="'+_ds.V(a)+'"></button>')},FH=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.V(a)+'" data-title="'+_ds.V(a)+'"></button>')},GH=function(a){a=a.label;return(0,_ds.T)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+
_ds.V(a)+'" data-title="'+_ds.V(a)+'"></button>')},HH=function(){var a=_ds.S.call(this,["devsite-snackbar"])||this;a.h=null;a.m=null;a.C=null;a.j=new _ds.Aj;a.H=!1;a.o=null;a.D=null;a.J=new _ds.Rp;a.L=new _ds.lr(_ds.rr(BH()));a.F=null;a.G=new _ds.Sp;return a},IH=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);c=_ds.Dr(a.L,
c);_ds.Dd(b,c);b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},JH=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");b.classList.remove("devsite-click-to-copy")}var c=
a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},KH=function(a){var b,c;return _ds.E(function(d){if(1==d.h){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);
_ds.as(document.body,b);if(!a.F)return d.K(0);c=new _ds.Rp;a.m.setAttribute("aria-label","Code sample copied to clipboard");_ds.Ej(a.j,a.F,_ds.Xu,function(){c.resolve()});return _ds.v(d,c.h,3)}_ds.Ej(a.j,a.F,_ds.Xu,function(){a.m.setAttribute("aria-label","Copy code sample to clipboard")});_ds.x(d)})},LH=function(a){a.C&&a.j.listen(a.C,"click",function(){return void a.setAttribute("dark-code","")});a.D&&a.j.listen(a.D,"click",function(){return void a.removeAttribute("dark-code")});a.m&&a.j.listen(a.m,
"click",function(){return void KH(a)});a.o&&a.j.listen(a.o,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.ps(c,b):_ds.os([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(Y){return Y.replace(w,"&amp;").replace(y,"&lt;").replace(A,"&gt;")}function b(Y,na,wa){switch(Y.nodeType){case 1:var Ha=Y.tagName.toLowerCase();na.push("<",Ha);var Ia=Y.attributes,$a=Ia.length;if($a){if(wa){for(var Sa=[],Ea=$a;0<=--Ea;)Sa[Ea]=Ia[Ea];Sa.sort(function(Fa,Ya){return Fa.name<Ya.name?-1:Fa.name===Ya.name?0:1});Ia=Sa}for(Ea=0;Ea<$a;++Ea)Sa=Ia[Ea],Sa.specified&&na.push(" ",Sa.name.toLowerCase(),'="',Sa.value.replace(w,"&amp;").replace(y,"&lt;").replace(A,"&gt;").replace(z,
"&quot;"),'"')}na.push(">");for(Ia=Y.firstChild;Ia;Ia=Ia.nextSibling)b(Ia,na,wa);!Y.firstChild&&/^(?:br|link|img)$/.test(Ha)||na.push("</",Ha,">");break;case 3:case 4:na.push(a(Y.nodeValue))}}function c(Y){function na(ma){if("\\"!==ma.charAt(0))return ma.charCodeAt(0);switch(ma.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(ma.substring(2),16)||ma.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(ma.substring(1),
8);default:return ma.charCodeAt(1)}}function wa(ma){if(32>ma)return(16>ma?"\\x0":"\\x")+ma.toString(16);ma=String.fromCharCode(ma);if("\\"===ma||"-"===ma||"["===ma||"]"===ma)ma="\\"+ma;return ma}function Ha(ma){var W=ma.substring(1,ma.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);ma=[];for(var fa=[],Ja="^"===W[0],sa=Ja?1:0,Ma=W.length;sa<Ma;++sa){var za=W[sa];switch(za){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":ma.push(za);
continue}za=na(za);if(sa+2<Ma&&"-"===W[sa+1]){var gb=na(W[sa+2]);sa+=2}else gb=za;fa.push([za,gb]);65>gb||122<za||(65>gb||90<za||fa.push([Math.max(65,za)|32,Math.min(gb,90)|32]),97>gb||122<za||fa.push([Math.max(97,za)&-33,Math.min(gb,122)&-33]))}fa.sort(function(rc,kh){return rc[0]-kh[0]||kh[1]-rc[1]});W=[];za=[NaN,NaN];for(sa=0;sa<fa.length;++sa)Ma=fa[sa],Ma[0]<=za[1]+1?za[1]=Math.max(za[1],Ma[1]):W.push(za=Ma);fa=["["];Ja&&fa.push("^");fa.push.apply(fa,ma);for(sa=0;sa<W.length;++sa)Ma=W[sa],fa.push(wa(Ma[0])),
Ma[1]>Ma[0]&&(Ma[1]+1>Ma[0]&&fa.push("-"),fa.push(wa(Ma[1])));fa.push("]");return fa.join("")}function Ia(ma){for(var W=ma.source.match(/(?:\[(?:[^\x5C\x5D]|\\[\s\S])*\]|\\u[A-Fa-f0-9]{4}|\\x[A-Fa-f0-9]{2}|\\[0-9]+|\\[^ux0-9]|\(\?[:!=]|[\(\)\^]|[^\x5B\x5C\(\)\^]+)/g),fa=W.length,Ja=[],sa=0,Ma=0;sa<fa;++sa){var za=W[sa];"("===za?++Ma:"\\"===za.charAt(0)&&(za=+za.substring(1))&&za<=Ma&&(Ja[za]=-1)}for(sa=1;sa<Ja.length;++sa)-1===Ja[sa]&&(Ja[sa]=++$a);for(Ma=sa=0;sa<fa;++sa)za=W[sa],"("===za?(++Ma,void 0===
Ja[Ma]&&(W[sa]="(?:")):"\\"===za.charAt(0)&&(za=+za.substring(1))&&za<=Ma&&(W[sa]="\\"+Ja[Ma]);for(Ma=sa=0;sa<fa;++sa)"^"===W[sa]&&"^"!==W[sa+1]&&(W[sa]="");if(ma.ignoreCase&&Sa)for(sa=0;sa<fa;++sa)za=W[sa],ma=za.charAt(0),2<=za.length&&"["===ma?W[sa]=Ha(za):"\\"!==ma&&(W[sa]=za.replace(/[a-zA-Z]/g,function(gb){gb=gb.charCodeAt(0);return"["+String.fromCharCode(gb&-33,gb|32)+"]"}));return W.join("")}for(var $a=0,Sa=!1,Ea=!1,Fa=0,Ya=Y.length;Fa<Ya;++Fa){var Va=Y[Fa];if(Va.ignoreCase)Ea=!0;else if(/[a-z]/i.test(Va.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,
""))){Sa=!0;Ea=!1;break}}var Pa=[];Fa=0;for(Ya=Y.length;Fa<Ya;++Fa){Va=Y[Fa];if(Va.global||Va.multiline)throw Error(""+Va);Pa.push("(?:"+Ia(Va)+")")}return new RegExp(Pa.join("|"),Ea?"gi":"g")}function d(Y){var na=0;return function(wa){for(var Ha=null,Ia=0,$a=0,Sa=wa.length;$a<Sa;++$a)switch(wa.charAt($a)){case "\t":Ha||(Ha=[]);Ha.push(wa.substring(Ia,$a));Ia=Y-na%Y;for(na+=Ia;0<=Ia;Ia-=16)Ha.push("                ".substring(0,Ia));Ia=$a+1;break;case "\n":na=0;break;default:++na}if(!Ha)return wa;
Ha.push(wa.substring(Ia));return Ha.join("")}}function e(Y,na,wa,Ha){na&&(Y={source:na,bh:Y},wa(Y),Ha.push.apply(Ha,Y.qh))}function g(Y,na){function wa(Sa){for(var Ea=Sa.bh,Fa=[Ea,"pln"],Ya=0,Va=Sa.source.match(Ia)||[],Pa={},ma=0,W=Va.length;ma<W;++ma){var fa=Va[ma],Ja=Pa[fa],sa=void 0;if("string"===typeof Ja)var Ma=!1;else{var za=Ha[fa.charAt(0)];if(za)sa=fa.match(za[1]),Ja=za[0];else{for(Ma=0;Ma<$a;++Ma)if(za=na[Ma],sa=fa.match(za[1])){Ja=za[0];break}sa||(Ja="pln")}!(Ma=5<=Ja.length&&"lang-"===
Ja.substring(0,5))||sa&&"string"===typeof sa[1]||(Ma=!1,Ja="src");Ma||(Pa[fa]=Ja)}za=Ya;Ya+=fa.length;if(Ma){Ma=sa[1];var gb=fa.indexOf(Ma),rc=gb+Ma.length;sa[2]&&(rc=fa.length-sa[2].length,gb=rc-Ma.length);Ja=Ja.substring(5);e(Ea+za,fa.substring(0,gb),wa,Fa);e(Ea+za+gb,Ma,q(Ja,Ma),Fa);e(Ea+za+rc,fa.substring(rc),wa,Fa)}else Fa.push(Ea+za,Ja)}Sa.qh=Fa}var Ha={},Ia;(function(){for(var Sa=Y.concat(na),Ea=[],Fa={},Ya=0,Va=Sa.length;Ya<Va;++Ya){var Pa=Sa[Ya],ma=Pa[3];if(ma)for(var W=ma.length;0<=--W;)Ha[ma.charAt(W)]=
Pa;Pa=Pa[1];ma=""+Pa;Fa.hasOwnProperty(ma)||(Ea.push(Pa),Fa[ma]=null)}Ea.push(/[\0-\uffff]/);Ia=c(Ea)})();var $a=na.length;return wa}function k(Y){var na=[],wa=[];Y.tripleQuotedStrings?na.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,null,"'\""]):Y.multiLineStrings?na.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,
null,"'\"`"]):na.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);Y.verbatimStrings&&wa.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var Ha=Y.hashComments;Ha&&(Y.cStyleComments?(1<Ha?na.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):na.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,null,"#"]),wa.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):
na.push(["com",/^#[^\r\n]*/,null,"#"]));Y.cStyleComments&&(wa.push(["com",/^\/\/[^\r\n]*/,null]),wa.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));Y.regexLiterals&&wa.push(["lang-regex",new RegExp("^"+t+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);Y=Y.keywords.replace(/^\s+|\s+$/g,"");Y.length&&wa.push(["kwd",new RegExp("^(?:"+Y.replace(/\s+/g,"|")+")\\b"),null]);na.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);wa.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,
null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return g(na,wa)}function m(Y){function na(gj){if(gj>Fa){Ya&&Ya!==Va&&(Ea.push("</span>"),Ya=null);!Ya&&Va&&(Ya=Va,Ea.push('<span class="',Ya,'">'));var fD=a(W(wa.substring(Fa,gj))).replace(za?Ja:fa,"$1&#160;");za=Ma.test(fD);Ea.push(fD.replace(sa,gD));Fa=gj}}var wa=Y.source,
Ha=Y.Hl,Ia=Y.qh,$a=Y.Di,Sa=Y.Cj,Ea=[],Fa=0,Ya=null,Va=null,Pa=0,ma=0,W=d(window.PR_TAB_WIDTH),fa=/([\r\n ]) /g,Ja=/(^| ) /gm,sa=/\r\n?|\n/g,Ma=/[ \r\n]$/,za=!0,gb=window._pr_isIE6();Sa=gb?Sa&&"PRE"===Sa.tagName?6===gb?"&#160;\r\n":7===gb?"&#160;<br />\r":8===gb?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if($a){var rc=[];for(gb=0;10>gb;++gb)rc[gb]=Sa+'</li><li class="L'+gb+'">';var kh="number"===typeof $a?$a-1:0;Ea.push('<ol class="linenums"><li class="L',kh%10,'"');kh&&Ea.push(' value="',kh+
1,'"');Ea.push(">");var gD=function(){var gj=rc[++kh%10];return Ya?"</span>"+gj+'<span class="'+Ya+'">':gj}}else gD=Sa;for(;;)if(Pa<Ha.length&&(ma<Ia.length?Ha[Pa]<=Ia[ma]:1))na(Ha[Pa]),Ya&&(Ea.push("</span>"),Ya=null),Ea.push(Ha[Pa+1]),Pa+=2;else if(ma<Ia.length)na(Ia[ma]),Va=Ia[ma+1],ma+=2;else break;na(wa.length);Ya&&Ea.push("</span>");$a&&Ea.push("</li></ol>");Y.Lf=Ea.join("")}function n(Y,na){for(var wa=na.length;0<=--wa;){var Ha=na[wa];Cc.hasOwnProperty(Ha)?"console"in window&&console.warn("cannot override language handler %s",
Ha):Cc[Ha]=Y}}function q(Y,na){Y&&Cc.hasOwnProperty(Y)||(Y=/^\s*</.test(na)?"default-markup":"default-code");return Cc[Y]}function r(Y){var na=Y.Bj,wa=Y.ai;Y.Lf=na;try{var Ha=na.match(Ra);na=[];var Ia=0,$a=[];if(Ha)for(var Sa=0,Ea=Ha.length;Sa<Ea;++Sa){var Fa=Ha[Sa];if(1<Fa.length&&"<"===Fa.charAt(0)){if(!Xa.test(Fa))if(Pb.test(Fa))na.push(Fa.substring(9,Fa.length-3)),Ia+=Fa.length-12;else if(gc.test(Fa))na.push("\n"),++Ia;else if(0<=Fa.indexOf("nocode")&&Fa.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,
' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Ya=Fa.match(Yb)[2],Va=1;var Pa=Sa+1;a:for(;Pa<Ea;++Pa){var ma=Ha[Pa].match(Yb);if(ma&&ma[2]===Ya)if("/"===ma[1]){if(0===--Va)break a}else++Va}Pa<Ea?($a.push(Ia,Ha.slice(Sa,Pa+1).join("")),Sa=Pa):$a.push(Ia,Fa)}else $a.push(Ia,Fa)}else{Va=Fa;var W=Va.indexOf("&");if(0>W)var fa=Va;else{for(--W;0<=(W=Va.indexOf("&#",W+1));){var Ja=Va.indexOf(";",W);if(0<=Ja){var sa=Va.substring(W+3,Ja),Ma=10;sa&&"x"===sa.charAt(0)&&(sa=sa.substring(1),
Ma=16);var za=parseInt(sa,Ma);isNaN(za)||(Va=Va.substring(0,W)+String.fromCharCode(za)+Va.substring(Ja+1))}}fa=Va.replace(ba,"<").replace(la,">").replace(P,"'").replace(Ka,'"').replace(jb," ").replace(qa,"&")}na.push(fa);Ia+=fa.length}}var gb=na.join("");Y.source=gb;Y.bh=0;Y.Hl=$a;q(wa,gb)(Y);m(Y)}catch(rc){"console"in window&&console.log(rc&&rc.stack?rc.stack:rc)}}var t=function(){for(var Y="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),
na="(?:^^|[+-]",wa=0;wa<Y.length;++wa)na+="|"+Y[wa].replace(/([^=<>:&a-z])/g,"\\$1");return na+")\\s*"}(),w=/&/g,y=/</g,A=/>/g,z=/"/g,ba=/&lt;/g,la=/&gt;/g,P=/&apos;/g,Ka=/&quot;/g,qa=/&amp;/g,jb=/&nbsp;/g,Ta=/[\r\n]/g,pa=null,Ra=/[^<]+|\x3c!--[\s\S]*?--\x3e|<!\[CDATA\[[\s\S]*?\]\]>|<\/?[a-zA-Z](?:[^>"']|'[^']*'|"[^"]*")*>|</g,Xa=/^\x3c!--/,Pb=/^<!\[CDATA\[/,gc=/^<br\b/i,Yb=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,Lc=k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Cc={};n(Lc,["default-code"]);n(g([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));n(g([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);n(g([],[["atv",/^[\s\S]+/]]),["uq.val"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));n(k({keywords:"null true false"}),["json"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);n(k({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);n(k({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);n(k({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);n(k({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);n(k({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);n(k({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);n(g([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(Y,na,wa){Y={Bj:Y,ai:na,Di:wa};r(Y);return Y.Lf};window.prettyPrint=function(Y){function na(){for(var Va=
window.PR_SHOULD_USE_CONTINUATION?Ea.now()+250:Infinity;Fa<Ha.length&&Ea.now()<Va;Fa++){var Pa=Ha[Fa];if(Pa.className&&0<=Pa.className.indexOf("prettyprint")){var ma=Pa.className.match(/\blang-(\w+)\b/);ma&&(ma=ma[1]);for(var W=!1,fa=Pa.parentNode;fa;fa=fa.parentNode)if(("pre"===fa.tagName||"code"===fa.tagName||"xmp"===fa.tagName)&&fa.className&&0<=fa.className.indexOf("prettyprint")){W=!0;break}if(!W){fa=Pa;null===pa&&(W=document.createElement("PRE"),W.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
pa=!/</.test(W.innerHTML));if(pa)if(W=fa.innerHTML,"XMP"===fa.tagName)W=a(W);else{if("PRE"!==fa.tagName&&Ta.test(W)){var Ja="";fa.currentStyle?Ja=fa.currentStyle.whiteSpace:window.getComputedStyle&&(Ja=window.getComputedStyle(fa,null).whiteSpace);fa=!Ja||"pre"===Ja}else fa=!0;fa||(W=W.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{W=[];for(fa=fa.firstChild;fa;fa=fa.nextSibling)b(fa,W);W=W.join("")}W=W.replace(/(?:\r\n?|\n)$/,"");fa=Pa.className.match(/\blinenums\b(?::(\d+))?/);
Ya={Bj:W,ai:ma,Cj:Pa,Di:fa?fa[1]&&fa[1].length?+fa[1]:!0:!1};r(Ya);if(Pa=Ya.Lf)if(ma=Ya.Cj,"XMP"===ma.tagName){W=document.createElement("PRE");for(fa=0;fa<ma.attributes.length;++fa)Ja=ma.attributes[fa],Ja.specified&&("class"===Ja.name.toLowerCase()?W.className=Ja.value:W.setAttribute(Ja.name,Ja.value));W.innerHTML=Pa;ma.parentNode.replaceChild(W,ma)}else ma.innerHTML=Pa}}}Fa<Ha.length?setTimeout(na,250):Y&&Y()}for(var wa=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],Ha=[],Ia=0;Ia<wa.length;++Ia)for(var $a=0,Sa=wa[Ia].length;$a<Sa;++$a)Ha.push(wa[Ia][$a]);wa=null;var Ea=Date;Ea.now||(Ea={now:function(){return(new Date).getTime()}});var Fa=0,Ya;na()};window.PR={combinePrefixPatterns:c,createSimpleLexer:g,registerLangHandler:n,sourceDecorator:k,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.u(HH,_ds.S);HH.prototype.whenReady=function(){return this.J.h};
HH.prototype.connectedCallback=function(){var a=this,b;return _ds.E(function(c){switch(c.h){case 1:return _ds.v(c,DevsiteApp.whenReady(),2);case 2:return a.H||(JH(a),IH(a),a.H=!0),a.G.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.J.resolve(),_ds.B(c,3),_ds.v(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.C(c,4);break;case 3:if(b=_ds.D(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");d?a.h=d:(a.h=
_ds.lm(CH),a.hasAttribute("scope")&&(a.o=_ds.lm(GH,{label:"Open code sample in JSFiddle"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.o.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.h.appendChild(a.o)),a.C=_ds.lm(DH,{label:"Dark code theme"}),a.h.appendChild(a.C),a.D=_ds.lm(EH,{label:"Light code theme"}),a.h.appendChild(a.D),a.hasAttribute("no-copy")||(a.m=_ds.lm(FH,{label:"Copy code sample to clipboard"}),a.h.appendChild(a.m)),
a.appendChild(a.h));LH(a);a.F=document.querySelector("devsite-snackbar");_ds.x(c)}})};HH.prototype.disconnectedCallback=function(){var a=this;return _ds.E(function(b){if(1==b.h)return _ds.v(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.h&&a.removeChild(a.h);_ds.Gj(a.j);_ds.x(b)})};
HH.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.E(function(e){if(1==e.h){if("dark-code"!==a||b===c)return e.K(0);if(d.hasAttribute("dark-code"))return d.G.set("pref_dark-code","1"),_ds.v(e,_ds.xi(),6);d.G.remove("pref_dark-code");return _ds.v(e,_ds.xi(),5)}if(6!=e.h)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(g){g.removeAttribute("dark-code")}),e.K(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(g){return g!==
d}).forEach(function(g){g.setAttribute("dark-code","")});_ds.x(e)})};_ds.l.Object.defineProperties(HH,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});HH.prototype.attributeChangedCallback=HH.prototype.attributeChangedCallback;HH.prototype.disconnectedCallback=HH.prototype.disconnectedCallback;HH.prototype.connectedCallback=HH.prototype.connectedCallback;HH.prototype.whenReady=HH.prototype.whenReady;try{window.customElements.define("devsite-code",HH)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
