(function(_ds){var window=this;'use strict';var ZG=function(){var a=_ds.S.call(this)||this;a.J=null;a.C=!1;a.j=null;a.h=null;a.m=new _ds.Aj;a.D=null;a.H=new Promise(function(b){a.D=b});a.G=new _ds.xj(function(){XG(a)},15);a.F=new _ds.xj(function(){YG(a)},20);a.o=new Set;return a},aH=function(a,b){b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.o=new Set(b);if(_ds.ji().hash){b=new _ds.Fr;a=_ds.p(a.o);for(var c=a.next();!c.done;c=a.next())_ds.Hr(b,c.value)}else $G(a,a.o)},$G=function(a,b){var c,d;_ds.E(function(e){if(1==
e.h)return _ds.v(e,DevsiteApp.whenReady(),2);c=new _ds.Fr;d=function(g){g=g.target;_ds.Hr(c,g);a.o.delete(g);DevsiteApp.unregisterIntersectionForElement(g)};b.forEach(function(g){try{DevsiteApp.registerIntersectionForElement(g,d)}catch(k){d({target:g})}});_ds.x(e)})},YG=function(a){a=0<a.getElementsByClassName("devsite-nav-item").length;var b=document.getElementById("devsite-hamburger-menu");b&&(a?b.removeAttribute("visually-hidden"):b.setAttribute("visually-hidden",""))},eH=function(a){a.m.listen(a,
"click",function(b){if(!b.defaultPrevented){var c=b.target;"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):a.setAttribute("top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&bH(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(c.classList.contains("devsite-nav-toggle")||
c.classList.contains("devsite-nav-title-no-path")||c.parentElement.classList.contains("devsite-nav-title-no-path"))){a.j&&(b=a.j.querySelector("[menu=_book]"))&&b.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var e;c instanceof Element&&c.matches("a.devsite-nav-title")?e=c:e=_ds.ph(c,"a","devsite-nav-title");e&&!e.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.m.listen(a,[cH,"focusin"],
function(b){return void dH(a,b)});a.m.listen(document.body,"devsite-sitemask-hidden",function(){a.j&&(bH(a,"_book")?a.removeAttribute("top-level-nav"):a.setAttribute("top-level-nav",""))});a.m.listen(document.body,"devsite-page-loaded",function(){return void a.F.oa()});a.m.listen(a,"devsite-content-updated",function(){a.F.oa();a.G.oa()});a.m.listen(a,"scroll",function(){return a.C=!0})},bH=function(a,b){var c=!1;Array.from(a.j.querySelectorAll("[menu]")).forEach(function(d){d.getAttribute("menu")===
b?(d.removeAttribute("hidden"),c=!0):d.setAttribute("hidden","")});return c},dH=function(a,b){b.defaultPrevented||(b=_ds.oh(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&_ds.Fd(b,_ds.qi(b.href).href))},fH=function(a){_ds.E(function(b){switch(b.h){case 1:return a.C=!1,_ds.v(b,_ds.xi(),2);case 2:return XG(a),_ds.v(b,a.H,3);case 3:return _ds.v(b,DevsiteApp.whenReady(),4);case 4:return _ds.v(b,_ds.xi(),5);case 5:XG(a),_ds.x(b)}})},gH=function(a,
b){(b=void 0===b?a:b)||(b=a);Array.from(b.getElementsByClassName("devsite-nav-active")).forEach(function(c){c.classList.remove("devsite-nav-active")});a=_ds.Bi(_ds.ji().pathname);a='[href="'+_ds.qi(a).href+'"], [href="'+a+'"],\n        [alt-paths*=" '+a+' "]';Array.from(b.querySelectorAll(a)).forEach(function(c){c.classList.add("devsite-nav-active")})},hH=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.getElementsByClassName("devsite-mobile-nav-bottom")[0];if(c){var d=c.getElementsByClassName("devsite-nav-active")[0];
if(d)for(;d.parentNode&&d.parentNode!=b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.Ej(a.m,d,"devsite-expandable-nav-transition-end",function(){d.setAttribute("animatable","")}),d.removeAttribute("collapsed")),d=d.parentNode}},XG=function(a){var b;_ds.E(function(c){if(1==c.h)return a.j?_ds.v(c,DevsiteApp.whenReady(),2):c.return();if(b=a.j.getElementsByClassName("devsite-nav-active")[0])a.C||iH(a,b),a.setAttribute("animatable","");_ds.x(c)})},iH=function(a,b){var c,d;_ds.E(function(e){if(1==
e.h)return c=a.C,"scrollIntoViewIfNeeded"in b?b.scrollIntoViewIfNeeded():(d=_ds.Tj(b,a,!0),a.scrollTop=d.y),_ds.v(e,_ds.xi(),2);a.C=c;_ds.x(e)})},jH=function(a){var b,c,d;_ds.E(function(e){if(1==e.h)return _ds.v(e,DevsiteApp.whenReady(),2);b=_ds.p(a.o);for(c=b.next();!c.done;c=b.next())d=c.value,DevsiteApp.unregisterIntersectionForElement(d);_ds.x(e)})},cH="onpointerover"in window?"pointerover":"mouseover";_ds.u(ZG,_ds.S);_ds.f=ZG.prototype;
_ds.f.connectedCallback=function(){this.h||(this.h=document.createElement("div"),this.h.classList.add("devsite-book-nav-bg"));_ds.Ng(this.h,this);YG(this);eH(this);this.Ga();this.setAttribute("animatable","");aH(this)};_ds.f.disconnectedCallback=function(){_ds.Gj(this.m);jH(this);this.o.clear();var a=document.getElementById("devsite-hamburger-menu");a&&a.setAttribute("visually-hidden","");this.h&&_ds.Qg(this.h);this.removeAttribute("animatable")};
_ds.f.attributeChangedCallback=function(a){if("hidden"==a){var b=this.hasAttribute("hidden");this.dispatchEvent(new CustomEvent(b?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));var c=document.getElementsByClassName("devsite-main-content")[0];c&&(b?c.removeAttribute("has-book-nav"):c.setAttribute("has-book-nav",""))}if("fixed"==a||"hidden"==a)b=this.hasAttribute(a),this.h&&(b?this.h.setAttribute(a,""):this.h.removeAttribute(a));"fixed"==a&&this.D()};
_ds.f.Ga=function(a){var b=this;a=void 0===a?!0:a;this.J=this.getElementsByClassName("devsite-book-nav")[0];this.j=this.getElementsByClassName("devsite-mobile-nav-bottom")[0];this.setAttribute("top-level-nav","");this.j&&this.j.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&this.setAttribute("hidden","");!this.hasAttribute("hidden")&&a&&(gH(this),hH(this),fH(this));this.h&&["hidden","fixed"].forEach(function(c){b.hasAttribute(c)&&b.h.setAttribute(c,
"")});!this.hasAttribute("hidden")&&this.j&&this.j.getElementsByClassName("devsite-nav-active")[0]||this.setAttribute("animatable","")};_ds.f.updateContent=function(a){var b=this;a?(this.removeAttribute("animatable"),a=_ds.nl(a).querySelector("nav"),gH(this,a),hH(this,a),a&&(jH(this),this.o.clear(),aH(this,a)),_ds.ol(this,this.getElementsByTagName("nav")[0],a),this.G.oa()):_ds.Mg(this);window.requestAnimationFrame(function(){b.Ga(!1)})};
_ds.l.Object.defineProperties(ZG,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["hidden","fixed"]}}});ZG.prototype.updateContent=ZG.prototype.updateContent;ZG.prototype.attributeChangedCallback=ZG.prototype.attributeChangedCallback;ZG.prototype.disconnectedCallback=ZG.prototype.disconnectedCallback;ZG.prototype.connectedCallback=ZG.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",ZG)}catch(a){console.warn("devsite.app.customElement.DevsiteBookNav",a)};})(_ds_www);
